//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TwinfieldApi.TwinfieldBudgetService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AuthenticationHeader", Namespace="http://schemas.datacontract.org/2004/07/Twinfield.WebServices.Shared")]
    [System.SerializableAttribute()]
    public partial class AuthenticationHeader : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AccessTokenField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CompanyCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.Guid> CompanyIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AccessToken {
            get {
                return this.AccessTokenField;
            }
            set {
                if ((object.ReferenceEquals(this.AccessTokenField, value) != true)) {
                    this.AccessTokenField = value;
                    this.RaisePropertyChanged("AccessToken");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CompanyCode {
            get {
                return this.CompanyCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.CompanyCodeField, value) != true)) {
                    this.CompanyCodeField = value;
                    this.RaisePropertyChanged("CompanyCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.Guid> CompanyId {
            get {
                return this.CompanyIdField;
            }
            set {
                if ((this.CompanyIdField.Equals(value) != true)) {
                    this.CompanyIdField = value;
                    this.RaisePropertyChanged("CompanyId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Command", Namespace="http://schemas.datacontract.org/2004/07/Twinfield.WebServices")]
    [System.SerializableAttribute()]
    public partial class Command : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SecurityFault", Namespace="http://schemas.datacontract.org/2004/07/Twinfield.WebServices")]
    [System.SerializableAttribute()]
    public partial class SecurityFault : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private TwinfieldApi.TwinfieldBudgetService.SecurityFaultCode CodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public TwinfieldApi.TwinfieldBudgetService.SecurityFaultCode Code {
            get {
                return this.CodeField;
            }
            set {
                if ((this.CodeField.Equals(value) != true)) {
                    this.CodeField = value;
                    this.RaisePropertyChanged("Code");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SecurityFaultCode", Namespace="http://schemas.datacontract.org/2004/07/Twinfield.WebServices")]
    public enum SecurityFaultCode : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Unexpected = 100,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        HeaderIsMissing = 101,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        AccessDenied = 102,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        LogonInvalid = 103,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        LogonDeleted = 104,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        LogonDisabled = 105,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        OrganisationInactive = 106,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        SmsSendFailed = 107,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        InvalidCluster = 108,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        SelectCompanyFailed = 109,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        InvalidLogonServer = 110,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ClientInvalid = 122,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        SameUserIsAlreadyLoggedIn = 168,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        LoggedOffByTwinfield = 169,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        InvalidZlibData = 186,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        InvalidXmlData = 187,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        AccessTokenUserCodeMissing = 351,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        AccessTokenOrganisationCodeMissing = 352,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        AccessTokenOrganisationIdMissing = 353,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        AccessTokenInvalid = 354,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        AccessTokenValidationUnavailable = 358,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        CompanyRequired = 359,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        TokenAndSessionExist = 360,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        CompanyIdAndCodeExist = 361,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        CompanyNotSupported = 362,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ValidationFault", Namespace="http://schemas.datacontract.org/2004/07/Twinfield.WebServices")]
    [System.SerializableAttribute()]
    public partial class ValidationFault : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Query", Namespace="http://schemas.datacontract.org/2004/07/Twinfield.WebServices")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(TwinfieldApi.TwinfieldBudgetService.BudgetQuery))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(TwinfieldApi.TwinfieldBudgetService.GetBudgetByProfitAndLoss))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(TwinfieldApi.TwinfieldBudgetService.GetBudgetByCostCenter))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(TwinfieldApi.TwinfieldBudgetService.GetBudgetByProject))]
    public partial class Query : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BudgetQuery", Namespace="http://schemas.datacontract.org/2004/07/Twinfield.WebServices.BudgetService")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(TwinfieldApi.TwinfieldBudgetService.GetBudgetByProfitAndLoss))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(TwinfieldApi.TwinfieldBudgetService.GetBudgetByCostCenter))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(TwinfieldApi.TwinfieldBudgetService.GetBudgetByProject))]
    public partial class BudgetQuery : TwinfieldApi.TwinfieldBudgetService.Query {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Dim1FromField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Dim1ToField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Dim2FromField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Dim2ToField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Dim3FromField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Dim3ToField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IncludeFinalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IncludeProvisionalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PeriodFromField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PeriodToField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private TwinfieldApi.TwinfieldBudgetService.RegimeType RegimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int YearField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Code {
            get {
                return this.CodeField;
            }
            set {
                if ((object.ReferenceEquals(this.CodeField, value) != true)) {
                    this.CodeField = value;
                    this.RaisePropertyChanged("Code");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Dim1From {
            get {
                return this.Dim1FromField;
            }
            set {
                if ((object.ReferenceEquals(this.Dim1FromField, value) != true)) {
                    this.Dim1FromField = value;
                    this.RaisePropertyChanged("Dim1From");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Dim1To {
            get {
                return this.Dim1ToField;
            }
            set {
                if ((object.ReferenceEquals(this.Dim1ToField, value) != true)) {
                    this.Dim1ToField = value;
                    this.RaisePropertyChanged("Dim1To");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Dim2From {
            get {
                return this.Dim2FromField;
            }
            set {
                if ((object.ReferenceEquals(this.Dim2FromField, value) != true)) {
                    this.Dim2FromField = value;
                    this.RaisePropertyChanged("Dim2From");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Dim2To {
            get {
                return this.Dim2ToField;
            }
            set {
                if ((object.ReferenceEquals(this.Dim2ToField, value) != true)) {
                    this.Dim2ToField = value;
                    this.RaisePropertyChanged("Dim2To");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Dim3From {
            get {
                return this.Dim3FromField;
            }
            set {
                if ((object.ReferenceEquals(this.Dim3FromField, value) != true)) {
                    this.Dim3FromField = value;
                    this.RaisePropertyChanged("Dim3From");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Dim3To {
            get {
                return this.Dim3ToField;
            }
            set {
                if ((object.ReferenceEquals(this.Dim3ToField, value) != true)) {
                    this.Dim3ToField = value;
                    this.RaisePropertyChanged("Dim3To");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IncludeFinal {
            get {
                return this.IncludeFinalField;
            }
            set {
                if ((this.IncludeFinalField.Equals(value) != true)) {
                    this.IncludeFinalField = value;
                    this.RaisePropertyChanged("IncludeFinal");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IncludeProvisional {
            get {
                return this.IncludeProvisionalField;
            }
            set {
                if ((this.IncludeProvisionalField.Equals(value) != true)) {
                    this.IncludeProvisionalField = value;
                    this.RaisePropertyChanged("IncludeProvisional");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PeriodFrom {
            get {
                return this.PeriodFromField;
            }
            set {
                if ((this.PeriodFromField.Equals(value) != true)) {
                    this.PeriodFromField = value;
                    this.RaisePropertyChanged("PeriodFrom");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PeriodTo {
            get {
                return this.PeriodToField;
            }
            set {
                if ((this.PeriodToField.Equals(value) != true)) {
                    this.PeriodToField = value;
                    this.RaisePropertyChanged("PeriodTo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public TwinfieldApi.TwinfieldBudgetService.RegimeType Regime {
            get {
                return this.RegimeField;
            }
            set {
                if ((this.RegimeField.Equals(value) != true)) {
                    this.RegimeField = value;
                    this.RaisePropertyChanged("Regime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Year {
            get {
                return this.YearField;
            }
            set {
                if ((this.YearField.Equals(value) != true)) {
                    this.YearField = value;
                    this.RaisePropertyChanged("Year");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetBudgetByProfitAndLoss", Namespace="http://schemas.datacontract.org/2004/07/Twinfield.WebServices.BudgetService")]
    [System.SerializableAttribute()]
    public partial class GetBudgetByProfitAndLoss : TwinfieldApi.TwinfieldBudgetService.BudgetQuery {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetBudgetByCostCenter", Namespace="http://schemas.datacontract.org/2004/07/Twinfield.WebServices.BudgetService")]
    [System.SerializableAttribute()]
    public partial class GetBudgetByCostCenter : TwinfieldApi.TwinfieldBudgetService.BudgetQuery {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetBudgetByProject", Namespace="http://schemas.datacontract.org/2004/07/Twinfield.WebServices.BudgetService")]
    [System.SerializableAttribute()]
    public partial class GetBudgetByProject : TwinfieldApi.TwinfieldBudgetService.BudgetQuery {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RegimeType", Namespace="http://schemas.datacontract.org/2004/07/Twinfield.Core.TransactionData")]
    public enum RegimeType : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Generic = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Fiscal = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Commercial = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Economic = 3,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="QueryResult", Namespace="http://schemas.datacontract.org/2004/07/Twinfield.WebServices")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(TwinfieldApi.TwinfieldBudgetService.GetBudgetTotalsResult))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(TwinfieldApi.TwinfieldBudgetService.GetBudgetTotalResult))]
    public partial class QueryResult : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetBudgetTotalsResult", Namespace="http://schemas.datacontract.org/2004/07/Twinfield.WebServices.BudgetService")]
    [System.SerializableAttribute()]
    public partial class GetBudgetTotalsResult : TwinfieldApi.TwinfieldBudgetService.QueryResult {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private TwinfieldApi.TwinfieldBudgetService.GetBudgetTotalResult[] BudgetTotalsField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public TwinfieldApi.TwinfieldBudgetService.GetBudgetTotalResult[] BudgetTotals {
            get {
                return this.BudgetTotalsField;
            }
            set {
                if ((object.ReferenceEquals(this.BudgetTotalsField, value) != true)) {
                    this.BudgetTotalsField = value;
                    this.RaisePropertyChanged("BudgetTotals");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetBudgetTotalResult", Namespace="http://schemas.datacontract.org/2004/07/Twinfield.WebServices.BudgetService")]
    [System.SerializableAttribute()]
    public partial class GetBudgetTotalResult : TwinfieldApi.TwinfieldBudgetService.QueryResult {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal ActualCreditField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal ActualDebitField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal ActualTotalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal BudgetCreditField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal BudgetDebitField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal BudgetTotalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Dim1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Dim2Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Dim3Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Group1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Group2Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Group3Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PeriodField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int YearField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal ActualCredit {
            get {
                return this.ActualCreditField;
            }
            set {
                if ((this.ActualCreditField.Equals(value) != true)) {
                    this.ActualCreditField = value;
                    this.RaisePropertyChanged("ActualCredit");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal ActualDebit {
            get {
                return this.ActualDebitField;
            }
            set {
                if ((this.ActualDebitField.Equals(value) != true)) {
                    this.ActualDebitField = value;
                    this.RaisePropertyChanged("ActualDebit");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal ActualTotal {
            get {
                return this.ActualTotalField;
            }
            set {
                if ((this.ActualTotalField.Equals(value) != true)) {
                    this.ActualTotalField = value;
                    this.RaisePropertyChanged("ActualTotal");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal BudgetCredit {
            get {
                return this.BudgetCreditField;
            }
            set {
                if ((this.BudgetCreditField.Equals(value) != true)) {
                    this.BudgetCreditField = value;
                    this.RaisePropertyChanged("BudgetCredit");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal BudgetDebit {
            get {
                return this.BudgetDebitField;
            }
            set {
                if ((this.BudgetDebitField.Equals(value) != true)) {
                    this.BudgetDebitField = value;
                    this.RaisePropertyChanged("BudgetDebit");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal BudgetTotal {
            get {
                return this.BudgetTotalField;
            }
            set {
                if ((this.BudgetTotalField.Equals(value) != true)) {
                    this.BudgetTotalField = value;
                    this.RaisePropertyChanged("BudgetTotal");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Dim1 {
            get {
                return this.Dim1Field;
            }
            set {
                if ((object.ReferenceEquals(this.Dim1Field, value) != true)) {
                    this.Dim1Field = value;
                    this.RaisePropertyChanged("Dim1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Dim2 {
            get {
                return this.Dim2Field;
            }
            set {
                if ((object.ReferenceEquals(this.Dim2Field, value) != true)) {
                    this.Dim2Field = value;
                    this.RaisePropertyChanged("Dim2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Dim3 {
            get {
                return this.Dim3Field;
            }
            set {
                if ((object.ReferenceEquals(this.Dim3Field, value) != true)) {
                    this.Dim3Field = value;
                    this.RaisePropertyChanged("Dim3");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Group1 {
            get {
                return this.Group1Field;
            }
            set {
                if ((object.ReferenceEquals(this.Group1Field, value) != true)) {
                    this.Group1Field = value;
                    this.RaisePropertyChanged("Group1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Group2 {
            get {
                return this.Group2Field;
            }
            set {
                if ((object.ReferenceEquals(this.Group2Field, value) != true)) {
                    this.Group2Field = value;
                    this.RaisePropertyChanged("Group2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Group3 {
            get {
                return this.Group3Field;
            }
            set {
                if ((object.ReferenceEquals(this.Group3Field, value) != true)) {
                    this.Group3Field = value;
                    this.RaisePropertyChanged("Group3");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Period {
            get {
                return this.PeriodField;
            }
            set {
                if ((this.PeriodField.Equals(value) != true)) {
                    this.PeriodField = value;
                    this.RaisePropertyChanged("Period");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Year {
            get {
                return this.YearField;
            }
            set {
                if ((this.YearField.Equals(value) != true)) {
                    this.YearField = value;
                    this.RaisePropertyChanged("Year");
                }
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.twinfield.com/", ConfigurationName="TwinfieldBudgetService.BudgetService")]
    public interface BudgetService {
        
        // CODEGEN: Generating message contract since the operation Process is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://www.twinfield.com/BudgetService/Process", ReplyAction="http://www.twinfield.com/BudgetService/ProcessResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(TwinfieldApi.TwinfieldBudgetService.SecurityFault), Action="http://www.twinfield.com/BudgetService/ProcessSecurityFaultFault", Name="SecurityFault", Namespace="http://schemas.datacontract.org/2004/07/Twinfield.WebServices")]
        [System.ServiceModel.FaultContractAttribute(typeof(TwinfieldApi.TwinfieldBudgetService.ValidationFault), Action="http://www.twinfield.com/BudgetService/ProcessValidationFaultFault", Name="ValidationFault", Namespace="http://schemas.datacontract.org/2004/07/Twinfield.WebServices")]
        TwinfieldApi.TwinfieldBudgetService.ProcessResponse Process(TwinfieldApi.TwinfieldBudgetService.CommandRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.twinfield.com/BudgetService/Process", ReplyAction="http://www.twinfield.com/BudgetService/ProcessResponse")]
        System.Threading.Tasks.Task<TwinfieldApi.TwinfieldBudgetService.ProcessResponse> ProcessAsync(TwinfieldApi.TwinfieldBudgetService.CommandRequest request);
        
        // CODEGEN: Generating message contract since the operation Query is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://www.twinfield.com/BudgetService/Query", ReplyAction="http://www.twinfield.com/BudgetService/QueryResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(TwinfieldApi.TwinfieldBudgetService.SecurityFault), Action="http://www.twinfield.com/BudgetService/QuerySecurityFaultFault", Name="SecurityFault", Namespace="http://schemas.datacontract.org/2004/07/Twinfield.WebServices")]
        [System.ServiceModel.FaultContractAttribute(typeof(TwinfieldApi.TwinfieldBudgetService.ValidationFault), Action="http://www.twinfield.com/BudgetService/QueryValidationFaultFault", Name="ValidationFault", Namespace="http://schemas.datacontract.org/2004/07/Twinfield.WebServices")]
        TwinfieldApi.TwinfieldBudgetService.QueryResponse Query(TwinfieldApi.TwinfieldBudgetService.QueryRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.twinfield.com/BudgetService/Query", ReplyAction="http://www.twinfield.com/BudgetService/QueryResponse")]
        System.Threading.Tasks.Task<TwinfieldApi.TwinfieldBudgetService.QueryResponse> QueryAsync(TwinfieldApi.TwinfieldBudgetService.QueryRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CommandRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://www.twinfield.com/")]
        public TwinfieldApi.TwinfieldBudgetService.AuthenticationHeader Authentication;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://www.twinfield.com/")]
        public string SessionId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.twinfield.com/", Order=0)]
        public TwinfieldApi.TwinfieldBudgetService.Command Command;
        
        public CommandRequest() {
        }
        
        public CommandRequest(TwinfieldApi.TwinfieldBudgetService.AuthenticationHeader Authentication, string SessionId, TwinfieldApi.TwinfieldBudgetService.Command Command) {
            this.Authentication = Authentication;
            this.SessionId = SessionId;
            this.Command = Command;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ProcessResponse {
        
        public ProcessResponse() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class QueryRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://www.twinfield.com/")]
        public TwinfieldApi.TwinfieldBudgetService.AuthenticationHeader Authentication;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://www.twinfield.com/")]
        public string SessionId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.twinfield.com/", Order=0)]
        public TwinfieldApi.TwinfieldBudgetService.Query Query;
        
        public QueryRequest() {
        }
        
        public QueryRequest(TwinfieldApi.TwinfieldBudgetService.AuthenticationHeader Authentication, string SessionId, TwinfieldApi.TwinfieldBudgetService.Query Query) {
            this.Authentication = Authentication;
            this.SessionId = SessionId;
            this.Query = Query;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class QueryResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.twinfield.com/", Order=0)]
        public TwinfieldApi.TwinfieldBudgetService.QueryResult Result;
        
        public QueryResponse() {
        }
        
        public QueryResponse(TwinfieldApi.TwinfieldBudgetService.QueryResult Result) {
            this.Result = Result;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface BudgetServiceChannel : TwinfieldApi.TwinfieldBudgetService.BudgetService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class BudgetServiceClient : System.ServiceModel.ClientBase<TwinfieldApi.TwinfieldBudgetService.BudgetService>, TwinfieldApi.TwinfieldBudgetService.BudgetService {
        
        public BudgetServiceClient() {
        }
        
        public BudgetServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public BudgetServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BudgetServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BudgetServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TwinfieldApi.TwinfieldBudgetService.ProcessResponse TwinfieldApi.TwinfieldBudgetService.BudgetService.Process(TwinfieldApi.TwinfieldBudgetService.CommandRequest request) {
            return base.Channel.Process(request);
        }
        
        public void Process(TwinfieldApi.TwinfieldBudgetService.AuthenticationHeader Authentication, string SessionId, TwinfieldApi.TwinfieldBudgetService.Command Command) {
            TwinfieldApi.TwinfieldBudgetService.CommandRequest inValue = new TwinfieldApi.TwinfieldBudgetService.CommandRequest();
            inValue.Authentication = Authentication;
            inValue.SessionId = SessionId;
            inValue.Command = Command;
            TwinfieldApi.TwinfieldBudgetService.ProcessResponse retVal = ((TwinfieldApi.TwinfieldBudgetService.BudgetService)(this)).Process(inValue);
        }

        public QueryResult Query(AuthenticationHeader Authentication, string SessionId, BudgetQuery Query1)
        {
            TwinfieldApi.TwinfieldBudgetService.QueryRequest inValue = new TwinfieldApi.TwinfieldBudgetService.QueryRequest();
            inValue.Authentication = Authentication;
            inValue.SessionId = SessionId;
            inValue.Query = Query1;
            TwinfieldApi.TwinfieldBudgetService.QueryResponse retVal = ((TwinfieldApi.TwinfieldBudgetService.BudgetService)(this)).Query(inValue);
            return retVal.Result;
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TwinfieldApi.TwinfieldBudgetService.ProcessResponse> TwinfieldApi.TwinfieldBudgetService.BudgetService.ProcessAsync(TwinfieldApi.TwinfieldBudgetService.CommandRequest request) {
            return base.Channel.ProcessAsync(request);
        }
        
        public System.Threading.Tasks.Task<TwinfieldApi.TwinfieldBudgetService.ProcessResponse> ProcessAsync(TwinfieldApi.TwinfieldBudgetService.AuthenticationHeader Authentication, string SessionId, TwinfieldApi.TwinfieldBudgetService.Command Command) {
            TwinfieldApi.TwinfieldBudgetService.CommandRequest inValue = new TwinfieldApi.TwinfieldBudgetService.CommandRequest();
            inValue.Authentication = Authentication;
            inValue.SessionId = SessionId;
            inValue.Command = Command;
            return ((TwinfieldApi.TwinfieldBudgetService.BudgetService)(this)).ProcessAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TwinfieldApi.TwinfieldBudgetService.QueryResponse TwinfieldApi.TwinfieldBudgetService.BudgetService.Query(TwinfieldApi.TwinfieldBudgetService.QueryRequest request) {
            return base.Channel.Query(request);
        }
        
        public TwinfieldApi.TwinfieldBudgetService.QueryResult Query(TwinfieldApi.TwinfieldBudgetService.AuthenticationHeader Authentication, string SessionId, TwinfieldApi.TwinfieldBudgetService.Query Query1) {
            TwinfieldApi.TwinfieldBudgetService.QueryRequest inValue = new TwinfieldApi.TwinfieldBudgetService.QueryRequest();
            inValue.Authentication = Authentication;
            inValue.SessionId = SessionId;
            inValue.Query = Query1;
            TwinfieldApi.TwinfieldBudgetService.QueryResponse retVal = ((TwinfieldApi.TwinfieldBudgetService.BudgetService)(this)).Query(inValue);
            return retVal.Result;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TwinfieldApi.TwinfieldBudgetService.QueryResponse> TwinfieldApi.TwinfieldBudgetService.BudgetService.QueryAsync(TwinfieldApi.TwinfieldBudgetService.QueryRequest request) {
            return base.Channel.QueryAsync(request);
        }
        
        public System.Threading.Tasks.Task<TwinfieldApi.TwinfieldBudgetService.QueryResponse> QueryAsync(TwinfieldApi.TwinfieldBudgetService.AuthenticationHeader Authentication, string SessionId, TwinfieldApi.TwinfieldBudgetService.Query Query) {
            TwinfieldApi.TwinfieldBudgetService.QueryRequest inValue = new TwinfieldApi.TwinfieldBudgetService.QueryRequest();
            inValue.Authentication = Authentication;
            inValue.SessionId = SessionId;
            inValue.Query = Query;
            return ((TwinfieldApi.TwinfieldBudgetService.BudgetService)(this)).QueryAsync(inValue);
        }

        public void Process(string SessionId, Command Command)
        {
            TwinfieldApi.TwinfieldBudgetService.CommandRequest inValue = new TwinfieldApi.TwinfieldBudgetService.CommandRequest();
            inValue.SessionId = SessionId;
            inValue.Command = Command;
            TwinfieldApi.TwinfieldBudgetService.ProcessResponse retVal =
                ((TwinfieldApi.TwinfieldBudgetService.BudgetService) (this)).Process(inValue);
        }

        public QueryResult Query(string SessionId, BudgetQuery Query1)
        {
            TwinfieldApi.TwinfieldBudgetService.QueryRequest inValue = new TwinfieldApi.TwinfieldBudgetService.QueryRequest();
            inValue.SessionId = SessionId;
            inValue.Query = Query1;
            TwinfieldApi.TwinfieldBudgetService.QueryResponse retValue =
                ((TwinfieldApi.TwinfieldBudgetService.BudgetService) (this)).Query(inValue);
            return retValue.Result;
        }
    }
}
