//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TwinfieldApi.TwinfieldPeriodService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AuthenticationHeader", Namespace="http://schemas.datacontract.org/2004/07/Twinfield.WebServices.Shared")]
    [System.SerializableAttribute()]
    public partial class AuthenticationHeader : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AccessTokenField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CompanyCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.Guid> CompanyIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AccessToken {
            get {
                return this.AccessTokenField;
            }
            set {
                if ((object.ReferenceEquals(this.AccessTokenField, value) != true)) {
                    this.AccessTokenField = value;
                    this.RaisePropertyChanged("AccessToken");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CompanyCode {
            get {
                return this.CompanyCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.CompanyCodeField, value) != true)) {
                    this.CompanyCodeField = value;
                    this.RaisePropertyChanged("CompanyCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.Guid> CompanyId {
            get {
                return this.CompanyIdField;
            }
            set {
                if ((this.CompanyIdField.Equals(value) != true)) {
                    this.CompanyIdField = value;
                    this.RaisePropertyChanged("CompanyId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Command", Namespace="http://schemas.datacontract.org/2004/07/Twinfield.WebServices")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(TwinfieldApi.TwinfieldPeriodService.DeleteYear))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(TwinfieldApi.TwinfieldPeriodService.ResetYears))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(TwinfieldApi.TwinfieldPeriodService.CreateYear))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(TwinfieldApi.TwinfieldPeriodService.ChangeEndDate))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(TwinfieldApi.TwinfieldPeriodService.ChangeName))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(TwinfieldApi.TwinfieldPeriodService.OpenPeriod))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(TwinfieldApi.TwinfieldPeriodService.ClosePeriod))]
    public partial class Command : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DeleteYear", Namespace="http://schemas.datacontract.org/2004/07/Twinfield.WebServices.PeriodService")]
    [System.SerializableAttribute()]
    public partial class DeleteYear : TwinfieldApi.TwinfieldPeriodService.Command {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int YearField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Year {
            get {
                return this.YearField;
            }
            set {
                if ((this.YearField.Equals(value) != true)) {
                    this.YearField = value;
                    this.RaisePropertyChanged("Year");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResetYears", Namespace="http://schemas.datacontract.org/2004/07/Twinfield.WebServices.PeriodService")]
    [System.SerializableAttribute()]
    public partial class ResetYears : TwinfieldApi.TwinfieldPeriodService.Command {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int NewNumberOfPeriodsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int NewYearField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int NewNumberOfPeriods {
            get {
                return this.NewNumberOfPeriodsField;
            }
            set {
                if ((this.NewNumberOfPeriodsField.Equals(value) != true)) {
                    this.NewNumberOfPeriodsField = value;
                    this.RaisePropertyChanged("NewNumberOfPeriods");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int NewYear {
            get {
                return this.NewYearField;
            }
            set {
                if ((this.NewYearField.Equals(value) != true)) {
                    this.NewYearField = value;
                    this.RaisePropertyChanged("NewYear");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CreateYear", Namespace="http://schemas.datacontract.org/2004/07/Twinfield.WebServices.PeriodService")]
    [System.SerializableAttribute()]
    public partial class CreateYear : TwinfieldApi.TwinfieldPeriodService.Command {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> NumberOfPeriodsField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> NumberOfPeriods {
            get {
                return this.NumberOfPeriodsField;
            }
            set {
                if ((this.NumberOfPeriodsField.Equals(value) != true)) {
                    this.NumberOfPeriodsField = value;
                    this.RaisePropertyChanged("NumberOfPeriods");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ChangeEndDate", Namespace="http://schemas.datacontract.org/2004/07/Twinfield.WebServices.PeriodService")]
    [System.SerializableAttribute()]
    public partial class ChangeEndDate : TwinfieldApi.TwinfieldPeriodService.Command {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime EndDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PeriodNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int YearField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime EndDate {
            get {
                return this.EndDateField;
            }
            set {
                if ((this.EndDateField.Equals(value) != true)) {
                    this.EndDateField = value;
                    this.RaisePropertyChanged("EndDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PeriodNumber {
            get {
                return this.PeriodNumberField;
            }
            set {
                if ((this.PeriodNumberField.Equals(value) != true)) {
                    this.PeriodNumberField = value;
                    this.RaisePropertyChanged("PeriodNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Year {
            get {
                return this.YearField;
            }
            set {
                if ((this.YearField.Equals(value) != true)) {
                    this.YearField = value;
                    this.RaisePropertyChanged("Year");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ChangeName", Namespace="http://schemas.datacontract.org/2004/07/Twinfield.WebServices.PeriodService")]
    [System.SerializableAttribute()]
    public partial class ChangeName : TwinfieldApi.TwinfieldPeriodService.Command {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PeriodNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int YearField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PeriodNumber {
            get {
                return this.PeriodNumberField;
            }
            set {
                if ((this.PeriodNumberField.Equals(value) != true)) {
                    this.PeriodNumberField = value;
                    this.RaisePropertyChanged("PeriodNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Year {
            get {
                return this.YearField;
            }
            set {
                if ((this.YearField.Equals(value) != true)) {
                    this.YearField = value;
                    this.RaisePropertyChanged("Year");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OpenPeriod", Namespace="http://schemas.datacontract.org/2004/07/Twinfield.WebServices.PeriodService")]
    [System.SerializableAttribute()]
    public partial class OpenPeriod : TwinfieldApi.TwinfieldPeriodService.Command {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PeriodNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int YearField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PeriodNumber {
            get {
                return this.PeriodNumberField;
            }
            set {
                if ((this.PeriodNumberField.Equals(value) != true)) {
                    this.PeriodNumberField = value;
                    this.RaisePropertyChanged("PeriodNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Year {
            get {
                return this.YearField;
            }
            set {
                if ((this.YearField.Equals(value) != true)) {
                    this.YearField = value;
                    this.RaisePropertyChanged("Year");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ClosePeriod", Namespace="http://schemas.datacontract.org/2004/07/Twinfield.WebServices.PeriodService")]
    [System.SerializableAttribute()]
    public partial class ClosePeriod : TwinfieldApi.TwinfieldPeriodService.Command {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PeriodNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int YearField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PeriodNumber {
            get {
                return this.PeriodNumberField;
            }
            set {
                if ((this.PeriodNumberField.Equals(value) != true)) {
                    this.PeriodNumberField = value;
                    this.RaisePropertyChanged("PeriodNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Year {
            get {
                return this.YearField;
            }
            set {
                if ((this.YearField.Equals(value) != true)) {
                    this.YearField = value;
                    this.RaisePropertyChanged("Year");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SecurityFault", Namespace="http://schemas.datacontract.org/2004/07/Twinfield.WebServices")]
    [System.SerializableAttribute()]
    public partial class SecurityFault : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private TwinfieldApi.TwinfieldPeriodService.SecurityFaultCode CodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public TwinfieldApi.TwinfieldPeriodService.SecurityFaultCode Code {
            get {
                return this.CodeField;
            }
            set {
                if ((this.CodeField.Equals(value) != true)) {
                    this.CodeField = value;
                    this.RaisePropertyChanged("Code");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SecurityFaultCode", Namespace="http://schemas.datacontract.org/2004/07/Twinfield.WebServices")]
    public enum SecurityFaultCode : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Unexpected = 100,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        HeaderIsMissing = 101,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        AccessDenied = 102,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        LogonInvalid = 103,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        LogonDeleted = 104,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        LogonDisabled = 105,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        OrganisationInactive = 106,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        SmsSendFailed = 107,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        InvalidCluster = 108,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        SelectCompanyFailed = 109,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        InvalidLogonServer = 110,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ClientInvalid = 122,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        SameUserIsAlreadyLoggedIn = 168,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        LoggedOffByTwinfield = 169,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        InvalidZlibData = 186,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        InvalidXmlData = 187,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        AccessTokenUserCodeMissing = 351,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        AccessTokenOrganisationCodeMissing = 352,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        AccessTokenOrganisationIdMissing = 353,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        AccessTokenInvalid = 354,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        AccessTokenValidationUnavailable = 358,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        CompanyRequired = 359,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        TokenAndSessionExist = 360,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        CompanyIdAndCodeExist = 361,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        CompanyNotSupported = 362,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ValidationFault", Namespace="http://schemas.datacontract.org/2004/07/Twinfield.WebServices")]
    [System.SerializableAttribute()]
    public partial class ValidationFault : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PeriodServiceFault", Namespace="http://schemas.datacontract.org/2004/07/Twinfield.WebServices.PeriodService")]
    [System.SerializableAttribute()]
    public partial class PeriodServiceFault : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private TwinfieldApi.TwinfieldPeriodService.PeriodServiceFaultCode CodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public TwinfieldApi.TwinfieldPeriodService.PeriodServiceFaultCode Code {
            get {
                return this.CodeField;
            }
            set {
                if ((this.CodeField.Equals(value) != true)) {
                    this.CodeField = value;
                    this.RaisePropertyChanged("Code");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PeriodServiceFaultCode", Namespace="http://schemas.datacontract.org/2004/07/Twinfield.WebServices.PeriodService")]
    public enum PeriodServiceFaultCode : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        YearNotFound = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        PeriodNotFound = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        YearCanNotBeDeleted = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        InvalidNumberOfPeriods = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        YearCanNotBeCreated = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        EndDateCanNotBeChanged = 5,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NameCanNotBeChanged = 6,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        PeriodCanNotBeOpened = 7,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        PeriodCanNotBeClosed = 8,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Query", Namespace="http://schemas.datacontract.org/2004/07/Twinfield.WebServices")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(TwinfieldApi.TwinfieldPeriodService.GetYears))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(TwinfieldApi.TwinfieldPeriodService.GetPeriods))]
    public partial class Query : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetYears", Namespace="http://schemas.datacontract.org/2004/07/Twinfield.WebServices.PeriodService")]
    [System.SerializableAttribute()]
    public partial class GetYears : TwinfieldApi.TwinfieldPeriodService.Query {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetPeriods", Namespace="http://schemas.datacontract.org/2004/07/Twinfield.WebServices.PeriodService")]
    [System.SerializableAttribute()]
    public partial class GetPeriods : TwinfieldApi.TwinfieldPeriodService.Query {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int YearField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Year {
            get {
                return this.YearField;
            }
            set {
                if ((this.YearField.Equals(value) != true)) {
                    this.YearField = value;
                    this.RaisePropertyChanged("Year");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="QueryResult", Namespace="http://schemas.datacontract.org/2004/07/Twinfield.WebServices")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(TwinfieldApi.TwinfieldPeriodService.GetYearsResult))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(TwinfieldApi.TwinfieldPeriodService.GetPeriodsResult))]
    public partial class QueryResult : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetYearsResult", Namespace="http://schemas.datacontract.org/2004/07/Twinfield.WebServices.PeriodService")]
    [System.SerializableAttribute()]
    public partial class GetYearsResult : TwinfieldApi.TwinfieldPeriodService.QueryResult {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int[] YearsField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int[] Years {
            get {
                return this.YearsField;
            }
            set {
                if ((object.ReferenceEquals(this.YearsField, value) != true)) {
                    this.YearsField = value;
                    this.RaisePropertyChanged("Years");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetPeriodsResult", Namespace="http://schemas.datacontract.org/2004/07/Twinfield.WebServices.PeriodService")]
    [System.SerializableAttribute()]
    public partial class GetPeriodsResult : TwinfieldApi.TwinfieldPeriodService.QueryResult {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private TwinfieldApi.TwinfieldPeriodService.Period[] PeriodsField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public TwinfieldApi.TwinfieldPeriodService.Period[] Periods {
            get {
                return this.PeriodsField;
            }
            set {
                if ((object.ReferenceEquals(this.PeriodsField, value) != true)) {
                    this.PeriodsField = value;
                    this.RaisePropertyChanged("Periods");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Period", Namespace="http://schemas.datacontract.org/2004/07/Twinfield.WebServices.PeriodService")]
    [System.SerializableAttribute()]
    public partial class Period : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> EndDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int NumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool OpenField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> EndDate {
            get {
                return this.EndDateField;
            }
            set {
                if ((this.EndDateField.Equals(value) != true)) {
                    this.EndDateField = value;
                    this.RaisePropertyChanged("EndDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Number {
            get {
                return this.NumberField;
            }
            set {
                if ((this.NumberField.Equals(value) != true)) {
                    this.NumberField = value;
                    this.RaisePropertyChanged("Number");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Open {
            get {
                return this.OpenField;
            }
            set {
                if ((this.OpenField.Equals(value) != true)) {
                    this.OpenField = value;
                    this.RaisePropertyChanged("Open");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.twinfield.com/", ConfigurationName="TwinfieldPeriodService.PeriodService")]
    public interface PeriodService {
        
        // CODEGEN: Generating message contract since the operation Process is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://www.twinfield.com/PeriodService/Process", ReplyAction="http://www.twinfield.com/PeriodService/ProcessResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(TwinfieldApi.TwinfieldPeriodService.SecurityFault), Action="http://www.twinfield.com/PeriodService/ProcessSecurityFaultFault", Name="SecurityFault", Namespace="http://schemas.datacontract.org/2004/07/Twinfield.WebServices")]
        [System.ServiceModel.FaultContractAttribute(typeof(TwinfieldApi.TwinfieldPeriodService.ValidationFault), Action="http://www.twinfield.com/PeriodService/ProcessValidationFaultFault", Name="ValidationFault", Namespace="http://schemas.datacontract.org/2004/07/Twinfield.WebServices")]
        [System.ServiceModel.FaultContractAttribute(typeof(TwinfieldApi.TwinfieldPeriodService.PeriodServiceFault), Action="http://www.twinfield.com/PeriodService/ProcessPeriodServiceFaultFault", Name="PeriodServiceFault", Namespace="http://schemas.datacontract.org/2004/07/Twinfield.WebServices.PeriodService")]
        TwinfieldApi.TwinfieldPeriodService.ProcessResponse Process(TwinfieldApi.TwinfieldPeriodService.CommandRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.twinfield.com/PeriodService/Process", ReplyAction="http://www.twinfield.com/PeriodService/ProcessResponse")]
        System.Threading.Tasks.Task<TwinfieldApi.TwinfieldPeriodService.ProcessResponse> ProcessAsync(TwinfieldApi.TwinfieldPeriodService.CommandRequest request);
        
        // CODEGEN: Generating message contract since the operation Query is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://www.twinfield.com/PeriodService/Query", ReplyAction="http://www.twinfield.com/PeriodService/QueryResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(TwinfieldApi.TwinfieldPeriodService.SecurityFault), Action="http://www.twinfield.com/PeriodService/QuerySecurityFaultFault", Name="SecurityFault", Namespace="http://schemas.datacontract.org/2004/07/Twinfield.WebServices")]
        [System.ServiceModel.FaultContractAttribute(typeof(TwinfieldApi.TwinfieldPeriodService.ValidationFault), Action="http://www.twinfield.com/PeriodService/QueryValidationFaultFault", Name="ValidationFault", Namespace="http://schemas.datacontract.org/2004/07/Twinfield.WebServices")]
        [System.ServiceModel.FaultContractAttribute(typeof(TwinfieldApi.TwinfieldPeriodService.PeriodServiceFault), Action="http://www.twinfield.com/PeriodService/QueryPeriodServiceFaultFault", Name="PeriodServiceFault", Namespace="http://schemas.datacontract.org/2004/07/Twinfield.WebServices.PeriodService")]
        TwinfieldApi.TwinfieldPeriodService.QueryResponse Query(TwinfieldApi.TwinfieldPeriodService.QueryRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.twinfield.com/PeriodService/Query", ReplyAction="http://www.twinfield.com/PeriodService/QueryResponse")]
        System.Threading.Tasks.Task<TwinfieldApi.TwinfieldPeriodService.QueryResponse> QueryAsync(TwinfieldApi.TwinfieldPeriodService.QueryRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CommandRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://www.twinfield.com/")]
        public TwinfieldApi.TwinfieldPeriodService.AuthenticationHeader Authentication;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://www.twinfield.com/")]
        public string SessionId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.twinfield.com/", Order=0)]
        public TwinfieldApi.TwinfieldPeriodService.Command Command;
        
        public CommandRequest() {
        }
        
        public CommandRequest(TwinfieldApi.TwinfieldPeriodService.AuthenticationHeader Authentication, string SessionId, TwinfieldApi.TwinfieldPeriodService.Command Command) {
            this.Authentication = Authentication;
            this.SessionId = SessionId;
            this.Command = Command;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ProcessResponse {
        
        public ProcessResponse() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class QueryRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://www.twinfield.com/")]
        public TwinfieldApi.TwinfieldPeriodService.AuthenticationHeader Authentication;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://www.twinfield.com/")]
        public string SessionId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.twinfield.com/", Order=0)]
        public TwinfieldApi.TwinfieldPeriodService.Query Query;
        
        public QueryRequest() {
        }
        
        public QueryRequest(TwinfieldApi.TwinfieldPeriodService.AuthenticationHeader Authentication, string SessionId, TwinfieldApi.TwinfieldPeriodService.Query Query) {
            this.Authentication = Authentication;
            this.SessionId = SessionId;
            this.Query = Query;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class QueryResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.twinfield.com/", Order=0)]
        public TwinfieldApi.TwinfieldPeriodService.QueryResult Result;
        
        public QueryResponse() {
        }
        
        public QueryResponse(TwinfieldApi.TwinfieldPeriodService.QueryResult Result) {
            this.Result = Result;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface PeriodServiceChannel : TwinfieldApi.TwinfieldPeriodService.PeriodService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PeriodServiceClient : System.ServiceModel.ClientBase<TwinfieldApi.TwinfieldPeriodService.PeriodService>, TwinfieldApi.TwinfieldPeriodService.PeriodService {
        
        public PeriodServiceClient() {
        }
        
        public PeriodServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PeriodServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PeriodServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PeriodServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TwinfieldApi.TwinfieldPeriodService.ProcessResponse TwinfieldApi.TwinfieldPeriodService.PeriodService.Process(TwinfieldApi.TwinfieldPeriodService.CommandRequest request) {
            return base.Channel.Process(request);
        }
        
        public void Process(TwinfieldApi.TwinfieldPeriodService.AuthenticationHeader Authentication, string SessionId, TwinfieldApi.TwinfieldPeriodService.Command Command) {
            TwinfieldApi.TwinfieldPeriodService.CommandRequest inValue = new TwinfieldApi.TwinfieldPeriodService.CommandRequest();
            inValue.Authentication = Authentication;
            inValue.SessionId = SessionId;
            inValue.Command = Command;
            TwinfieldApi.TwinfieldPeriodService.ProcessResponse retVal = ((TwinfieldApi.TwinfieldPeriodService.PeriodService)(this)).Process(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TwinfieldApi.TwinfieldPeriodService.ProcessResponse> TwinfieldApi.TwinfieldPeriodService.PeriodService.ProcessAsync(TwinfieldApi.TwinfieldPeriodService.CommandRequest request) {
            return base.Channel.ProcessAsync(request);
        }
        
        public System.Threading.Tasks.Task<TwinfieldApi.TwinfieldPeriodService.ProcessResponse> ProcessAsync(TwinfieldApi.TwinfieldPeriodService.AuthenticationHeader Authentication, string SessionId, TwinfieldApi.TwinfieldPeriodService.Command Command) {
            TwinfieldApi.TwinfieldPeriodService.CommandRequest inValue = new TwinfieldApi.TwinfieldPeriodService.CommandRequest();
            inValue.Authentication = Authentication;
            inValue.SessionId = SessionId;
            inValue.Command = Command;
            return ((TwinfieldApi.TwinfieldPeriodService.PeriodService)(this)).ProcessAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TwinfieldApi.TwinfieldPeriodService.QueryResponse TwinfieldApi.TwinfieldPeriodService.PeriodService.Query(TwinfieldApi.TwinfieldPeriodService.QueryRequest request) {
            return base.Channel.Query(request);
        }
        
        public TwinfieldApi.TwinfieldPeriodService.QueryResult Query(TwinfieldApi.TwinfieldPeriodService.AuthenticationHeader Authentication, string SessionId, TwinfieldApi.TwinfieldPeriodService.Query Query1) {
            TwinfieldApi.TwinfieldPeriodService.QueryRequest inValue = new TwinfieldApi.TwinfieldPeriodService.QueryRequest();
            inValue.Authentication = Authentication;
            inValue.SessionId = SessionId;
            inValue.Query = Query1;
            TwinfieldApi.TwinfieldPeriodService.QueryResponse retVal = ((TwinfieldApi.TwinfieldPeriodService.PeriodService)(this)).Query(inValue);
            return retVal.Result;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TwinfieldApi.TwinfieldPeriodService.QueryResponse> TwinfieldApi.TwinfieldPeriodService.PeriodService.QueryAsync(TwinfieldApi.TwinfieldPeriodService.QueryRequest request) {
            return base.Channel.QueryAsync(request);
        }
        
        public System.Threading.Tasks.Task<TwinfieldApi.TwinfieldPeriodService.QueryResponse> QueryAsync(TwinfieldApi.TwinfieldPeriodService.AuthenticationHeader Authentication, string SessionId, TwinfieldApi.TwinfieldPeriodService.Query Query) {
            TwinfieldApi.TwinfieldPeriodService.QueryRequest inValue = new TwinfieldApi.TwinfieldPeriodService.QueryRequest();
            inValue.Authentication = Authentication;
            inValue.SessionId = SessionId;
            inValue.Query = Query;
            return ((TwinfieldApi.TwinfieldPeriodService.PeriodService)(this)).QueryAsync(inValue);
        }

        public void Process(string SessionId, Command Command)
        {
            TwinfieldApi.TwinfieldPeriodService.CommandRequest inValue = new TwinfieldApi.TwinfieldPeriodService.CommandRequest();
            inValue.SessionId = SessionId;
            inValue.Command = Command;
            TwinfieldApi.TwinfieldPeriodService.ProcessResponse retVal =
                ((TwinfieldApi.TwinfieldPeriodService.PeriodService) (this)).Process(inValue);
        }

        public QueryResult Query(string SessionId, Query Query)
        {
            TwinfieldApi.TwinfieldPeriodService.QueryRequest inValue = new TwinfieldApi.TwinfieldPeriodService.QueryRequest();
            inValue.SessionId = SessionId;
            inValue.Query = Query;
            TwinfieldApi.TwinfieldPeriodService.QueryResponse retVal =
                ((TwinfieldApi.TwinfieldPeriodService.PeriodService) (this)).Query(inValue);
            return retVal.Result;
        }
    }
}
