//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TwinfieldApi.TwinfieldDeletedTransactionService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AuthenticationHeader", Namespace="http://schemas.datacontract.org/2004/07/Twinfield.WebServices.Shared")]
    [System.SerializableAttribute()]
    public partial class AuthenticationHeader : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AccessTokenField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CompanyCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.Guid> CompanyIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AccessToken {
            get {
                return this.AccessTokenField;
            }
            set {
                if ((object.ReferenceEquals(this.AccessTokenField, value) != true)) {
                    this.AccessTokenField = value;
                    this.RaisePropertyChanged("AccessToken");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CompanyCode {
            get {
                return this.CompanyCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.CompanyCodeField, value) != true)) {
                    this.CompanyCodeField = value;
                    this.RaisePropertyChanged("CompanyCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.Guid> CompanyId {
            get {
                return this.CompanyIdField;
            }
            set {
                if ((this.CompanyIdField.Equals(value) != true)) {
                    this.CompanyIdField = value;
                    this.RaisePropertyChanged("CompanyId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Query", Namespace="http://schemas.datacontract.org/2004/07/Twinfield.WebServices")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(TwinfieldApi.TwinfieldDeletedTransactionService.GetDeletedTransactions))]
    public partial class Query : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetDeletedTransactions", Namespace="http://schemas.datacontract.org/2004/07/Twinfield.WebServices.DeletedTransactions" +
        "Service")]
    [System.SerializableAttribute()]
    public partial class GetDeletedTransactions : TwinfieldApi.TwinfieldDeletedTransactionService.Query {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CompanyCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> DateFromField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> DateToField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DaybookField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CompanyCode {
            get {
                return this.CompanyCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.CompanyCodeField, value) != true)) {
                    this.CompanyCodeField = value;
                    this.RaisePropertyChanged("CompanyCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> DateFrom {
            get {
                return this.DateFromField;
            }
            set {
                if ((this.DateFromField.Equals(value) != true)) {
                    this.DateFromField = value;
                    this.RaisePropertyChanged("DateFrom");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> DateTo {
            get {
                return this.DateToField;
            }
            set {
                if ((this.DateToField.Equals(value) != true)) {
                    this.DateToField = value;
                    this.RaisePropertyChanged("DateTo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Daybook {
            get {
                return this.DaybookField;
            }
            set {
                if ((object.ReferenceEquals(this.DaybookField, value) != true)) {
                    this.DaybookField = value;
                    this.RaisePropertyChanged("Daybook");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="QueryResult", Namespace="http://schemas.datacontract.org/2004/07/Twinfield.WebServices")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(TwinfieldApi.TwinfieldDeletedTransactionService.GetDeletedTransactionsResult))]
    public partial class QueryResult : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetDeletedTransactionsResult", Namespace="http://schemas.datacontract.org/2004/07/Twinfield.WebServices.DeletedTransactions" +
        "Service")]
    [System.SerializableAttribute()]
    public partial class GetDeletedTransactionsResult : TwinfieldApi.TwinfieldDeletedTransactionService.QueryResult {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private TwinfieldApi.TwinfieldDeletedTransactionService.DeletedTransaction[] DeletedTransactionsField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public TwinfieldApi.TwinfieldDeletedTransactionService.DeletedTransaction[] DeletedTransactions {
            get {
                return this.DeletedTransactionsField;
            }
            set {
                if ((object.ReferenceEquals(this.DeletedTransactionsField, value) != true)) {
                    this.DeletedTransactionsField = value;
                    this.RaisePropertyChanged("DeletedTransactions");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DeletedTransaction", Namespace="http://schemas.datacontract.org/2004/07/Twinfield.WebServices.DeletedTransactions" +
        "Service")]
    [System.SerializableAttribute()]
    public partial class DeletedTransaction : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DaybookField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DeletionDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ReasonForDeletionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime TransactionDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal TransactionNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Daybook {
            get {
                return this.DaybookField;
            }
            set {
                if ((object.ReferenceEquals(this.DaybookField, value) != true)) {
                    this.DaybookField = value;
                    this.RaisePropertyChanged("Daybook");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime DeletionDate {
            get {
                return this.DeletionDateField;
            }
            set {
                if ((this.DeletionDateField.Equals(value) != true)) {
                    this.DeletionDateField = value;
                    this.RaisePropertyChanged("DeletionDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ReasonForDeletion {
            get {
                return this.ReasonForDeletionField;
            }
            set {
                if ((object.ReferenceEquals(this.ReasonForDeletionField, value) != true)) {
                    this.ReasonForDeletionField = value;
                    this.RaisePropertyChanged("ReasonForDeletion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime TransactionDate {
            get {
                return this.TransactionDateField;
            }
            set {
                if ((this.TransactionDateField.Equals(value) != true)) {
                    this.TransactionDateField = value;
                    this.RaisePropertyChanged("TransactionDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal TransactionNumber {
            get {
                return this.TransactionNumberField;
            }
            set {
                if ((this.TransactionNumberField.Equals(value) != true)) {
                    this.TransactionNumberField = value;
                    this.RaisePropertyChanged("TransactionNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string User {
            get {
                return this.UserField;
            }
            set {
                if ((object.ReferenceEquals(this.UserField, value) != true)) {
                    this.UserField = value;
                    this.RaisePropertyChanged("User");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SecurityFault", Namespace="http://schemas.datacontract.org/2004/07/Twinfield.WebServices")]
    [System.SerializableAttribute()]
    public partial class SecurityFault : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private TwinfieldApi.TwinfieldDeletedTransactionService.SecurityFaultCode CodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public TwinfieldApi.TwinfieldDeletedTransactionService.SecurityFaultCode Code {
            get {
                return this.CodeField;
            }
            set {
                if ((this.CodeField.Equals(value) != true)) {
                    this.CodeField = value;
                    this.RaisePropertyChanged("Code");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SecurityFaultCode", Namespace="http://schemas.datacontract.org/2004/07/Twinfield.WebServices")]
    public enum SecurityFaultCode : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Unexpected = 100,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        HeaderIsMissing = 101,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        AccessDenied = 102,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        LogonInvalid = 103,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        LogonDeleted = 104,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        LogonDisabled = 105,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        OrganisationInactive = 106,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        SmsSendFailed = 107,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        InvalidCluster = 108,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        SelectCompanyFailed = 109,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        InvalidLogonServer = 110,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ClientInvalid = 122,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        SameUserIsAlreadyLoggedIn = 168,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        LoggedOffByTwinfield = 169,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        InvalidZlibData = 186,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        InvalidXmlData = 187,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        AccessTokenUserCodeMissing = 351,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        AccessTokenOrganisationCodeMissing = 352,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        AccessTokenOrganisationIdMissing = 353,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        AccessTokenInvalid = 354,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        AccessTokenValidationUnavailable = 358,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        CompanyRequired = 359,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        TokenAndSessionExist = 360,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        CompanyIdAndCodeExist = 361,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        CompanyNotSupported = 362,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ValidationFault", Namespace="http://schemas.datacontract.org/2004/07/Twinfield.WebServices")]
    [System.SerializableAttribute()]
    public partial class ValidationFault : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DeletedTransactionsServiceFault", Namespace="http://schemas.datacontract.org/2004/07/Twinfield.WebServices.DeletedTransactions" +
        "Service")]
    [System.SerializableAttribute()]
    public partial class DeletedTransactionsServiceFault : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private TwinfieldApi.TwinfieldDeletedTransactionService.DeletedTransactionsServiceFaultCode CodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public TwinfieldApi.TwinfieldDeletedTransactionService.DeletedTransactionsServiceFaultCode Code {
            get {
                return this.CodeField;
            }
            set {
                if ((this.CodeField.Equals(value) != true)) {
                    this.CodeField = value;
                    this.RaisePropertyChanged("Code");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DeletedTransactionsServiceFaultCode", Namespace="http://schemas.datacontract.org/2004/07/Twinfield.WebServices.DeletedTransactions" +
        "Service")]
    public enum DeletedTransactionsServiceFaultCode : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        InvalidCompanyCode = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        InvalidDaybook = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        InvalidDates = 2,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.twinfield.com/", ConfigurationName="TwinfieldDeletedTransactionService.DeletedTransactionsService")]
    public interface DeletedTransactionsService {
        
        // CODEGEN: Generating message contract since the operation Query is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://www.twinfield.com/DeletedTransactionsService/Query", ReplyAction="http://www.twinfield.com/DeletedTransactionsService/QueryResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(TwinfieldApi.TwinfieldDeletedTransactionService.SecurityFault), Action="http://www.twinfield.com/DeletedTransactionsService/QuerySecurityFaultFault", Name="SecurityFault", Namespace="http://schemas.datacontract.org/2004/07/Twinfield.WebServices")]
        [System.ServiceModel.FaultContractAttribute(typeof(TwinfieldApi.TwinfieldDeletedTransactionService.ValidationFault), Action="http://www.twinfield.com/DeletedTransactionsService/QueryValidationFaultFault", Name="ValidationFault", Namespace="http://schemas.datacontract.org/2004/07/Twinfield.WebServices")]
        [System.ServiceModel.FaultContractAttribute(typeof(TwinfieldApi.TwinfieldDeletedTransactionService.DeletedTransactionsServiceFault), Action="http://www.twinfield.com/DeletedTransactionsService/QueryDeletedTransactionsServi" +
            "ceFaultFault", Name="DeletedTransactionsServiceFault", Namespace="http://schemas.datacontract.org/2004/07/Twinfield.WebServices.DeletedTransactions" +
            "Service")]
        TwinfieldApi.TwinfieldDeletedTransactionService.QueryResponse Query(TwinfieldApi.TwinfieldDeletedTransactionService.QueryRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.twinfield.com/DeletedTransactionsService/Query", ReplyAction="http://www.twinfield.com/DeletedTransactionsService/QueryResponse")]
        System.Threading.Tasks.Task<TwinfieldApi.TwinfieldDeletedTransactionService.QueryResponse> QueryAsync(TwinfieldApi.TwinfieldDeletedTransactionService.QueryRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class QueryRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://www.twinfield.com/")]
        public TwinfieldApi.TwinfieldDeletedTransactionService.AuthenticationHeader Authentication;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://www.twinfield.com/")]
        public string SessionId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.twinfield.com/", Order=0)]
        public TwinfieldApi.TwinfieldDeletedTransactionService.Query Query;
        
        public QueryRequest() {
        }
        
        public QueryRequest(TwinfieldApi.TwinfieldDeletedTransactionService.AuthenticationHeader Authentication, string SessionId, TwinfieldApi.TwinfieldDeletedTransactionService.Query Query) {
            this.Authentication = Authentication;
            this.SessionId = SessionId;
            this.Query = Query;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class QueryResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.twinfield.com/", Order=0)]
        public TwinfieldApi.TwinfieldDeletedTransactionService.QueryResult Result;
        
        public QueryResponse() {
        }
        
        public QueryResponse(TwinfieldApi.TwinfieldDeletedTransactionService.QueryResult Result) {
            this.Result = Result;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface DeletedTransactionsServiceChannel : TwinfieldApi.TwinfieldDeletedTransactionService.DeletedTransactionsService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DeletedTransactionsServiceClient : System.ServiceModel.ClientBase<TwinfieldApi.TwinfieldDeletedTransactionService.DeletedTransactionsService>, TwinfieldApi.TwinfieldDeletedTransactionService.DeletedTransactionsService {
        
        public DeletedTransactionsServiceClient() {
        }
        
        public DeletedTransactionsServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public DeletedTransactionsServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DeletedTransactionsServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DeletedTransactionsServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TwinfieldApi.TwinfieldDeletedTransactionService.QueryResponse TwinfieldApi.TwinfieldDeletedTransactionService.DeletedTransactionsService.Query(TwinfieldApi.TwinfieldDeletedTransactionService.QueryRequest request) {
            return base.Channel.Query(request);
        }
        
        public TwinfieldApi.TwinfieldDeletedTransactionService.QueryResult Query(TwinfieldApi.TwinfieldDeletedTransactionService.AuthenticationHeader Authentication, string SessionId, TwinfieldApi.TwinfieldDeletedTransactionService.Query Query1) {
            TwinfieldApi.TwinfieldDeletedTransactionService.QueryRequest inValue = new TwinfieldApi.TwinfieldDeletedTransactionService.QueryRequest();
            inValue.Authentication = Authentication;
            inValue.SessionId = SessionId;
            inValue.Query = Query1;
            TwinfieldApi.TwinfieldDeletedTransactionService.QueryResponse retVal = ((TwinfieldApi.TwinfieldDeletedTransactionService.DeletedTransactionsService)(this)).Query(inValue);
            return retVal.Result;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TwinfieldApi.TwinfieldDeletedTransactionService.QueryResponse> TwinfieldApi.TwinfieldDeletedTransactionService.DeletedTransactionsService.QueryAsync(TwinfieldApi.TwinfieldDeletedTransactionService.QueryRequest request) {
            return base.Channel.QueryAsync(request);
        }
        
        public System.Threading.Tasks.Task<TwinfieldApi.TwinfieldDeletedTransactionService.QueryResponse> QueryAsync(TwinfieldApi.TwinfieldDeletedTransactionService.AuthenticationHeader Authentication, string SessionId, TwinfieldApi.TwinfieldDeletedTransactionService.Query Query) {
            TwinfieldApi.TwinfieldDeletedTransactionService.QueryRequest inValue = new TwinfieldApi.TwinfieldDeletedTransactionService.QueryRequest();
            inValue.Authentication = Authentication;
            inValue.SessionId = SessionId;
            inValue.Query = Query;
            return ((TwinfieldApi.TwinfieldDeletedTransactionService.DeletedTransactionsService)(this)).QueryAsync(inValue);
        }

        public QueryResult Query(string SessionId, Query Query)
        {
            TwinfieldApi.TwinfieldDeletedTransactionService.QueryRequest inValue = new TwinfieldApi.TwinfieldDeletedTransactionService.QueryRequest();
            inValue.SessionId = SessionId;
            inValue.Query = Query;
            TwinfieldApi.TwinfieldDeletedTransactionService.QueryResponse retVal =
                ((TwinfieldApi.TwinfieldDeletedTransactionService.DeletedTransactionsService) (this)).Query(inValue);
            return retVal.Result;

        }
    }
}
