//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DemoConnector.TwinfieldSessionService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.twinfield.com/", ConfigurationName="TwinfieldSessionService.SessionSoap")]
    public interface SessionSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.twinfield.com/Logon", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        DemoConnector.TwinfieldSessionService.LogonResponse Logon(DemoConnector.TwinfieldSessionService.LogonRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://www.twinfield.com/Logon", ReplyAction="*")]
        System.Threading.Tasks.Task<DemoConnector.TwinfieldSessionService.LogonResponse> LogonAsync(DemoConnector.TwinfieldSessionService.LogonRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.twinfield.com/SmsLogon", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        DemoConnector.TwinfieldSessionService.SmsLogonResponse SmsLogon(DemoConnector.TwinfieldSessionService.SmsLogonRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://www.twinfield.com/SmsLogon", ReplyAction="*")]
        System.Threading.Tasks.Task<DemoConnector.TwinfieldSessionService.SmsLogonResponse> SmsLogonAsync(DemoConnector.TwinfieldSessionService.SmsLogonRequest request);
        
        // CODEGEN: Generating message contract since message SmsSendCodeRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="http://www.twinfield.com/SmsSendCode", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        DemoConnector.TwinfieldSessionService.SmsSendCodeResponse SmsSendCode(DemoConnector.TwinfieldSessionService.SmsSendCodeRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.twinfield.com/SmsSendCode", ReplyAction="*")]
        System.Threading.Tasks.Task<DemoConnector.TwinfieldSessionService.SmsSendCodeResponse> SmsSendCodeAsync(DemoConnector.TwinfieldSessionService.SmsSendCodeRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.twinfield.com/ChangePassword", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        DemoConnector.TwinfieldSessionService.ChangePasswordResponse ChangePassword(DemoConnector.TwinfieldSessionService.ChangePasswordRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://www.twinfield.com/ChangePassword", ReplyAction="*")]
        System.Threading.Tasks.Task<DemoConnector.TwinfieldSessionService.ChangePasswordResponse> ChangePasswordAsync(DemoConnector.TwinfieldSessionService.ChangePasswordRequest request);
        
        // CODEGEN: Generating message contract since message SelectCompanyRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="http://www.twinfield.com/SelectCompany", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        DemoConnector.TwinfieldSessionService.SelectCompanyResponse SelectCompany(DemoConnector.TwinfieldSessionService.SelectCompanyRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.twinfield.com/SelectCompany", ReplyAction="*")]
        System.Threading.Tasks.Task<DemoConnector.TwinfieldSessionService.SelectCompanyResponse> SelectCompanyAsync(DemoConnector.TwinfieldSessionService.SelectCompanyRequest request);
        
        // CODEGEN: Generating message contract since message KeepAliveRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="http://www.twinfield.com/KeepAlive", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        DemoConnector.TwinfieldSessionService.KeepAliveResponse KeepAlive(DemoConnector.TwinfieldSessionService.KeepAliveRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.twinfield.com/KeepAlive", ReplyAction="*")]
        System.Threading.Tasks.Task<DemoConnector.TwinfieldSessionService.KeepAliveResponse> KeepAliveAsync(DemoConnector.TwinfieldSessionService.KeepAliveRequest request);
        
        // CODEGEN: Generating message contract since message AbandonRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="http://www.twinfield.com/Abandon", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        DemoConnector.TwinfieldSessionService.AbandonResponse Abandon(DemoConnector.TwinfieldSessionService.AbandonRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.twinfield.com/Abandon", ReplyAction="*")]
        System.Threading.Tasks.Task<DemoConnector.TwinfieldSessionService.AbandonResponse> AbandonAsync(DemoConnector.TwinfieldSessionService.AbandonRequest request);
        
        // CODEGEN: Generating message contract since message GetRoleRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="http://www.twinfield.com/GetRole", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        DemoConnector.TwinfieldSessionService.GetRoleResponse GetRole(DemoConnector.TwinfieldSessionService.GetRoleRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.twinfield.com/GetRole", ReplyAction="*")]
        System.Threading.Tasks.Task<DemoConnector.TwinfieldSessionService.GetRoleResponse> GetRoleAsync(DemoConnector.TwinfieldSessionService.GetRoleRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.twinfield.com/")]
    public partial class Header : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string sessionIDField;
        
        private string accessTokenField;
        
        private string companyCodeField;
        
        private System.Nullable<System.Guid> companyIdField;
        
        private System.Xml.XmlAttribute[] anyAttrField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string SessionID {
            get {
                return this.sessionIDField;
            }
            set {
                this.sessionIDField = value;
                this.RaisePropertyChanged("SessionID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string AccessToken {
            get {
                return this.accessTokenField;
            }
            set {
                this.accessTokenField = value;
                this.RaisePropertyChanged("AccessToken");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string CompanyCode {
            get {
                return this.companyCodeField;
            }
            set {
                this.companyCodeField = value;
                this.RaisePropertyChanged("CompanyCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=3)]
        public System.Nullable<System.Guid> CompanyId {
            get {
                return this.companyIdField;
            }
            set {
                this.companyIdField = value;
                this.RaisePropertyChanged("CompanyId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyAttributeAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr {
            get {
                return this.anyAttrField;
            }
            set {
                this.anyAttrField = value;
                this.RaisePropertyChanged("AnyAttr");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.twinfield.com/")]
    public enum LogonResult {
        
        /// <remarks/>
        Ok,
        
        /// <remarks/>
        Blocked,
        
        /// <remarks/>
        Untrusted,
        
        /// <remarks/>
        Invalid,
        
        /// <remarks/>
        Deleted,
        
        /// <remarks/>
        Disabled,
        
        /// <remarks/>
        OrganisationInactive,
        
        /// <remarks/>
        ClientInvalid,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.twinfield.com/")]
    public enum LogonAction {
        
        /// <remarks/>
        None,
        
        /// <remarks/>
        SMSLogon,
        
        /// <remarks/>
        ChangePassword,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Logon", WrapperNamespace="http://www.twinfield.com/", IsWrapped=true)]
    public partial class LogonRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.twinfield.com/", Order=0)]
        public string user;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.twinfield.com/", Order=1)]
        public string password;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.twinfield.com/", Order=2)]
        public string organisation;
        
        public LogonRequest() {
        }
        
        public LogonRequest(string user, string password, string organisation) {
            this.user = user;
            this.password = password;
            this.organisation = organisation;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="LogonResponse", WrapperNamespace="http://www.twinfield.com/", IsWrapped=true)]
    public partial class LogonResponse {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://www.twinfield.com/")]
        public DemoConnector.TwinfieldSessionService.Header Header;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.twinfield.com/", Order=0)]
        public DemoConnector.TwinfieldSessionService.LogonResult LogonResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.twinfield.com/", Order=1)]
        public DemoConnector.TwinfieldSessionService.LogonAction nextAction;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.twinfield.com/", Order=2)]
        public string cluster;
        
        public LogonResponse() {
        }
        
        public LogonResponse(DemoConnector.TwinfieldSessionService.Header Header, DemoConnector.TwinfieldSessionService.LogonResult LogonResult, DemoConnector.TwinfieldSessionService.LogonAction nextAction, string cluster) {
            this.Header = Header;
            this.LogonResult = LogonResult;
            this.nextAction = nextAction;
            this.cluster = cluster;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.twinfield.com/")]
    public enum SMSLogonResult {
        
        /// <remarks/>
        Ok,
        
        /// <remarks/>
        Invalid,
        
        /// <remarks/>
        TimeOut,
        
        /// <remarks/>
        Disabled,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SmsLogon", WrapperNamespace="http://www.twinfield.com/", IsWrapped=true)]
    public partial class SmsLogonRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://www.twinfield.com/")]
        public DemoConnector.TwinfieldSessionService.Header Header;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.twinfield.com/", Order=0)]
        public string smsCode;
        
        public SmsLogonRequest() {
        }
        
        public SmsLogonRequest(DemoConnector.TwinfieldSessionService.Header Header, string smsCode) {
            this.Header = Header;
            this.smsCode = smsCode;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SmsLogonResponse", WrapperNamespace="http://www.twinfield.com/", IsWrapped=true)]
    public partial class SmsLogonResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.twinfield.com/", Order=0)]
        public DemoConnector.TwinfieldSessionService.SMSLogonResult SmsLogonResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.twinfield.com/", Order=1)]
        public DemoConnector.TwinfieldSessionService.LogonAction nextAction;
        
        public SmsLogonResponse() {
        }
        
        public SmsLogonResponse(DemoConnector.TwinfieldSessionService.SMSLogonResult SmsLogonResult, DemoConnector.TwinfieldSessionService.LogonAction nextAction) {
            this.SmsLogonResult = SmsLogonResult;
            this.nextAction = nextAction;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SmsSendCode", WrapperNamespace="http://www.twinfield.com/", IsWrapped=true)]
    public partial class SmsSendCodeRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://www.twinfield.com/")]
        public DemoConnector.TwinfieldSessionService.Header Header;
        
        public SmsSendCodeRequest() {
        }
        
        public SmsSendCodeRequest(DemoConnector.TwinfieldSessionService.Header Header) {
            this.Header = Header;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SmsSendCodeResponse", WrapperNamespace="http://www.twinfield.com/", IsWrapped=true)]
    public partial class SmsSendCodeResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.twinfield.com/", Order=0)]
        public int SmsSendCodeResult;
        
        public SmsSendCodeResponse() {
        }
        
        public SmsSendCodeResponse(int SmsSendCodeResult) {
            this.SmsSendCodeResult = SmsSendCodeResult;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.twinfield.com/")]
    public enum ChangePasswordResult {
        
        /// <remarks/>
        Ok,
        
        /// <remarks/>
        Invalid,
        
        /// <remarks/>
        NotDifferent,
        
        /// <remarks/>
        NotSecure,
        
        /// <remarks/>
        Disabled,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ChangePassword", WrapperNamespace="http://www.twinfield.com/", IsWrapped=true)]
    public partial class ChangePasswordRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://www.twinfield.com/")]
        public DemoConnector.TwinfieldSessionService.Header Header;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.twinfield.com/", Order=0)]
        public string currentPassword;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.twinfield.com/", Order=1)]
        public string newPassword;
        
        public ChangePasswordRequest() {
        }
        
        public ChangePasswordRequest(DemoConnector.TwinfieldSessionService.Header Header, string currentPassword, string newPassword) {
            this.Header = Header;
            this.currentPassword = currentPassword;
            this.newPassword = newPassword;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ChangePasswordResponse", WrapperNamespace="http://www.twinfield.com/", IsWrapped=true)]
    public partial class ChangePasswordResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.twinfield.com/", Order=0)]
        public DemoConnector.TwinfieldSessionService.ChangePasswordResult ChangePasswordResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.twinfield.com/", Order=1)]
        public DemoConnector.TwinfieldSessionService.LogonAction nextAction;
        
        public ChangePasswordResponse() {
        }
        
        public ChangePasswordResponse(DemoConnector.TwinfieldSessionService.ChangePasswordResult ChangePasswordResult, DemoConnector.TwinfieldSessionService.LogonAction nextAction) {
            this.ChangePasswordResult = ChangePasswordResult;
            this.nextAction = nextAction;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.twinfield.com/")]
    public enum SelectCompanyResult {
        
        /// <remarks/>
        Ok,
        
        /// <remarks/>
        Invalid,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SelectCompany", WrapperNamespace="http://www.twinfield.com/", IsWrapped=true)]
    public partial class SelectCompanyRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://www.twinfield.com/")]
        public DemoConnector.TwinfieldSessionService.Header Header;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.twinfield.com/", Order=0)]
        public string company;
        
        public SelectCompanyRequest() {
        }
        
        public SelectCompanyRequest(DemoConnector.TwinfieldSessionService.Header Header, string company) {
            this.Header = Header;
            this.company = company;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SelectCompanyResponse", WrapperNamespace="http://www.twinfield.com/", IsWrapped=true)]
    public partial class SelectCompanyResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.twinfield.com/", Order=0)]
        public DemoConnector.TwinfieldSessionService.SelectCompanyResult SelectCompanyResult;
        
        public SelectCompanyResponse() {
        }
        
        public SelectCompanyResponse(DemoConnector.TwinfieldSessionService.SelectCompanyResult SelectCompanyResult) {
            this.SelectCompanyResult = SelectCompanyResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="KeepAlive", WrapperNamespace="http://www.twinfield.com/", IsWrapped=true)]
    public partial class KeepAliveRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://www.twinfield.com/")]
        public DemoConnector.TwinfieldSessionService.Header Header;
        
        public KeepAliveRequest() {
        }
        
        public KeepAliveRequest(DemoConnector.TwinfieldSessionService.Header Header) {
            this.Header = Header;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="KeepAliveResponse", WrapperNamespace="http://www.twinfield.com/", IsWrapped=true)]
    public partial class KeepAliveResponse {
        
        public KeepAliveResponse() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Abandon", WrapperNamespace="http://www.twinfield.com/", IsWrapped=true)]
    public partial class AbandonRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://www.twinfield.com/")]
        public DemoConnector.TwinfieldSessionService.Header Header;
        
        public AbandonRequest() {
        }
        
        public AbandonRequest(DemoConnector.TwinfieldSessionService.Header Header) {
            this.Header = Header;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AbandonResponse", WrapperNamespace="http://www.twinfield.com/", IsWrapped=true)]
    public partial class AbandonResponse {
        
        public AbandonResponse() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetRole", WrapperNamespace="http://www.twinfield.com/", IsWrapped=true)]
    public partial class GetRoleRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://www.twinfield.com/")]
        public DemoConnector.TwinfieldSessionService.Header Header;
        
        public GetRoleRequest() {
        }
        
        public GetRoleRequest(DemoConnector.TwinfieldSessionService.Header Header) {
            this.Header = Header;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetRoleResponse", WrapperNamespace="http://www.twinfield.com/", IsWrapped=true)]
    public partial class GetRoleResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.twinfield.com/", Order=0)]
        public string GetRoleResult;
        
        public GetRoleResponse() {
        }
        
        public GetRoleResponse(string GetRoleResult) {
            this.GetRoleResult = GetRoleResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface SessionSoapChannel : DemoConnector.TwinfieldSessionService.SessionSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SessionSoapClient : System.ServiceModel.ClientBase<DemoConnector.TwinfieldSessionService.SessionSoap>, DemoConnector.TwinfieldSessionService.SessionSoap {
        
        public SessionSoapClient() {
        }
        
        public SessionSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SessionSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SessionSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SessionSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DemoConnector.TwinfieldSessionService.LogonResponse DemoConnector.TwinfieldSessionService.SessionSoap.Logon(DemoConnector.TwinfieldSessionService.LogonRequest request) {
            return base.Channel.Logon(request);
        }
        
        public DemoConnector.TwinfieldSessionService.Header Logon(string user, string password, string organisation, out DemoConnector.TwinfieldSessionService.LogonResult LogonResult, out DemoConnector.TwinfieldSessionService.LogonAction nextAction, out string cluster) {
            DemoConnector.TwinfieldSessionService.LogonRequest inValue = new DemoConnector.TwinfieldSessionService.LogonRequest();
            inValue.user = user;
            inValue.password = password;
            inValue.organisation = organisation;
            DemoConnector.TwinfieldSessionService.LogonResponse retVal = ((DemoConnector.TwinfieldSessionService.SessionSoap)(this)).Logon(inValue);
            LogonResult = retVal.LogonResult;
            nextAction = retVal.nextAction;
            cluster = retVal.cluster;
            return retVal.Header;
        }
        
        public System.Threading.Tasks.Task<DemoConnector.TwinfieldSessionService.LogonResponse> LogonAsync(DemoConnector.TwinfieldSessionService.LogonRequest request) {
            return base.Channel.LogonAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DemoConnector.TwinfieldSessionService.SmsLogonResponse DemoConnector.TwinfieldSessionService.SessionSoap.SmsLogon(DemoConnector.TwinfieldSessionService.SmsLogonRequest request) {
            return base.Channel.SmsLogon(request);
        }
        
        public DemoConnector.TwinfieldSessionService.SMSLogonResult SmsLogon(DemoConnector.TwinfieldSessionService.Header Header, string smsCode, out DemoConnector.TwinfieldSessionService.LogonAction nextAction) {
            DemoConnector.TwinfieldSessionService.SmsLogonRequest inValue = new DemoConnector.TwinfieldSessionService.SmsLogonRequest();
            inValue.Header = Header;
            inValue.smsCode = smsCode;
            DemoConnector.TwinfieldSessionService.SmsLogonResponse retVal = ((DemoConnector.TwinfieldSessionService.SessionSoap)(this)).SmsLogon(inValue);
            nextAction = retVal.nextAction;
            return retVal.SmsLogonResult;
        }
        
        public System.Threading.Tasks.Task<DemoConnector.TwinfieldSessionService.SmsLogonResponse> SmsLogonAsync(DemoConnector.TwinfieldSessionService.SmsLogonRequest request) {
            return base.Channel.SmsLogonAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DemoConnector.TwinfieldSessionService.SmsSendCodeResponse DemoConnector.TwinfieldSessionService.SessionSoap.SmsSendCode(DemoConnector.TwinfieldSessionService.SmsSendCodeRequest request) {
            return base.Channel.SmsSendCode(request);
        }
        
        public int SmsSendCode(DemoConnector.TwinfieldSessionService.Header Header) {
            DemoConnector.TwinfieldSessionService.SmsSendCodeRequest inValue = new DemoConnector.TwinfieldSessionService.SmsSendCodeRequest();
            inValue.Header = Header;
            DemoConnector.TwinfieldSessionService.SmsSendCodeResponse retVal = ((DemoConnector.TwinfieldSessionService.SessionSoap)(this)).SmsSendCode(inValue);
            return retVal.SmsSendCodeResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<DemoConnector.TwinfieldSessionService.SmsSendCodeResponse> DemoConnector.TwinfieldSessionService.SessionSoap.SmsSendCodeAsync(DemoConnector.TwinfieldSessionService.SmsSendCodeRequest request) {
            return base.Channel.SmsSendCodeAsync(request);
        }
        
        public System.Threading.Tasks.Task<DemoConnector.TwinfieldSessionService.SmsSendCodeResponse> SmsSendCodeAsync(DemoConnector.TwinfieldSessionService.Header Header) {
            DemoConnector.TwinfieldSessionService.SmsSendCodeRequest inValue = new DemoConnector.TwinfieldSessionService.SmsSendCodeRequest();
            inValue.Header = Header;
            return ((DemoConnector.TwinfieldSessionService.SessionSoap)(this)).SmsSendCodeAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DemoConnector.TwinfieldSessionService.ChangePasswordResponse DemoConnector.TwinfieldSessionService.SessionSoap.ChangePassword(DemoConnector.TwinfieldSessionService.ChangePasswordRequest request) {
            return base.Channel.ChangePassword(request);
        }
        
        public DemoConnector.TwinfieldSessionService.ChangePasswordResult ChangePassword(DemoConnector.TwinfieldSessionService.Header Header, string currentPassword, string newPassword, out DemoConnector.TwinfieldSessionService.LogonAction nextAction) {
            DemoConnector.TwinfieldSessionService.ChangePasswordRequest inValue = new DemoConnector.TwinfieldSessionService.ChangePasswordRequest();
            inValue.Header = Header;
            inValue.currentPassword = currentPassword;
            inValue.newPassword = newPassword;
            DemoConnector.TwinfieldSessionService.ChangePasswordResponse retVal = ((DemoConnector.TwinfieldSessionService.SessionSoap)(this)).ChangePassword(inValue);
            nextAction = retVal.nextAction;
            return retVal.ChangePasswordResult;
        }
        
        public System.Threading.Tasks.Task<DemoConnector.TwinfieldSessionService.ChangePasswordResponse> ChangePasswordAsync(DemoConnector.TwinfieldSessionService.ChangePasswordRequest request) {
            return base.Channel.ChangePasswordAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DemoConnector.TwinfieldSessionService.SelectCompanyResponse DemoConnector.TwinfieldSessionService.SessionSoap.SelectCompany(DemoConnector.TwinfieldSessionService.SelectCompanyRequest request) {
            return base.Channel.SelectCompany(request);
        }
        
        public DemoConnector.TwinfieldSessionService.SelectCompanyResult SelectCompany(DemoConnector.TwinfieldSessionService.Header Header, string company) {
            DemoConnector.TwinfieldSessionService.SelectCompanyRequest inValue = new DemoConnector.TwinfieldSessionService.SelectCompanyRequest();
            inValue.Header = Header;
            inValue.company = company;
            DemoConnector.TwinfieldSessionService.SelectCompanyResponse retVal = ((DemoConnector.TwinfieldSessionService.SessionSoap)(this)).SelectCompany(inValue);
            return retVal.SelectCompanyResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<DemoConnector.TwinfieldSessionService.SelectCompanyResponse> DemoConnector.TwinfieldSessionService.SessionSoap.SelectCompanyAsync(DemoConnector.TwinfieldSessionService.SelectCompanyRequest request) {
            return base.Channel.SelectCompanyAsync(request);
        }
        
        public System.Threading.Tasks.Task<DemoConnector.TwinfieldSessionService.SelectCompanyResponse> SelectCompanyAsync(DemoConnector.TwinfieldSessionService.Header Header, string company) {
            DemoConnector.TwinfieldSessionService.SelectCompanyRequest inValue = new DemoConnector.TwinfieldSessionService.SelectCompanyRequest();
            inValue.Header = Header;
            inValue.company = company;
            return ((DemoConnector.TwinfieldSessionService.SessionSoap)(this)).SelectCompanyAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DemoConnector.TwinfieldSessionService.KeepAliveResponse DemoConnector.TwinfieldSessionService.SessionSoap.KeepAlive(DemoConnector.TwinfieldSessionService.KeepAliveRequest request) {
            return base.Channel.KeepAlive(request);
        }
        
        public void KeepAlive(DemoConnector.TwinfieldSessionService.Header Header) {
            DemoConnector.TwinfieldSessionService.KeepAliveRequest inValue = new DemoConnector.TwinfieldSessionService.KeepAliveRequest();
            inValue.Header = Header;
            DemoConnector.TwinfieldSessionService.KeepAliveResponse retVal = ((DemoConnector.TwinfieldSessionService.SessionSoap)(this)).KeepAlive(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<DemoConnector.TwinfieldSessionService.KeepAliveResponse> DemoConnector.TwinfieldSessionService.SessionSoap.KeepAliveAsync(DemoConnector.TwinfieldSessionService.KeepAliveRequest request) {
            return base.Channel.KeepAliveAsync(request);
        }
        
        public System.Threading.Tasks.Task<DemoConnector.TwinfieldSessionService.KeepAliveResponse> KeepAliveAsync(DemoConnector.TwinfieldSessionService.Header Header) {
            DemoConnector.TwinfieldSessionService.KeepAliveRequest inValue = new DemoConnector.TwinfieldSessionService.KeepAliveRequest();
            inValue.Header = Header;
            return ((DemoConnector.TwinfieldSessionService.SessionSoap)(this)).KeepAliveAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DemoConnector.TwinfieldSessionService.AbandonResponse DemoConnector.TwinfieldSessionService.SessionSoap.Abandon(DemoConnector.TwinfieldSessionService.AbandonRequest request) {
            return base.Channel.Abandon(request);
        }
        
        public void Abandon(DemoConnector.TwinfieldSessionService.Header Header) {
            DemoConnector.TwinfieldSessionService.AbandonRequest inValue = new DemoConnector.TwinfieldSessionService.AbandonRequest();
            inValue.Header = Header;
            DemoConnector.TwinfieldSessionService.AbandonResponse retVal = ((DemoConnector.TwinfieldSessionService.SessionSoap)(this)).Abandon(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<DemoConnector.TwinfieldSessionService.AbandonResponse> DemoConnector.TwinfieldSessionService.SessionSoap.AbandonAsync(DemoConnector.TwinfieldSessionService.AbandonRequest request) {
            return base.Channel.AbandonAsync(request);
        }
        
        public System.Threading.Tasks.Task<DemoConnector.TwinfieldSessionService.AbandonResponse> AbandonAsync(DemoConnector.TwinfieldSessionService.Header Header) {
            DemoConnector.TwinfieldSessionService.AbandonRequest inValue = new DemoConnector.TwinfieldSessionService.AbandonRequest();
            inValue.Header = Header;
            return ((DemoConnector.TwinfieldSessionService.SessionSoap)(this)).AbandonAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DemoConnector.TwinfieldSessionService.GetRoleResponse DemoConnector.TwinfieldSessionService.SessionSoap.GetRole(DemoConnector.TwinfieldSessionService.GetRoleRequest request) {
            return base.Channel.GetRole(request);
        }
        
        public string GetRole(DemoConnector.TwinfieldSessionService.Header Header) {
            DemoConnector.TwinfieldSessionService.GetRoleRequest inValue = new DemoConnector.TwinfieldSessionService.GetRoleRequest();
            inValue.Header = Header;
            DemoConnector.TwinfieldSessionService.GetRoleResponse retVal = ((DemoConnector.TwinfieldSessionService.SessionSoap)(this)).GetRole(inValue);
            return retVal.GetRoleResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<DemoConnector.TwinfieldSessionService.GetRoleResponse> DemoConnector.TwinfieldSessionService.SessionSoap.GetRoleAsync(DemoConnector.TwinfieldSessionService.GetRoleRequest request) {
            return base.Channel.GetRoleAsync(request);
        }
        
        public System.Threading.Tasks.Task<DemoConnector.TwinfieldSessionService.GetRoleResponse> GetRoleAsync(DemoConnector.TwinfieldSessionService.Header Header) {
            DemoConnector.TwinfieldSessionService.GetRoleRequest inValue = new DemoConnector.TwinfieldSessionService.GetRoleRequest();
            inValue.Header = Header;
            return ((DemoConnector.TwinfieldSessionService.SessionSoap)(this)).GetRoleAsync(inValue);
        }
    }
}
