//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Collections.Generic;
using System.Linq;

namespace TwinfieldApi.TwinfieldDeclarationsService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.twinfield.com/", ConfigurationName="TwinfieldDeclarationsService.DeclarationsSoap")]
    public interface DeclarationsSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.twinfield.com/GetAllSummaries", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        TwinfieldApi.TwinfieldDeclarationsService.GetAllSummariesResponse GetAllSummaries(TwinfieldApi.TwinfieldDeclarationsService.GetAllSummariesRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://www.twinfield.com/GetAllSummaries", ReplyAction="*")]
        System.Threading.Tasks.Task<TwinfieldApi.TwinfieldDeclarationsService.GetAllSummariesResponse> GetAllSummariesAsync(TwinfieldApi.TwinfieldDeclarationsService.GetAllSummariesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.twinfield.com/GetRangeOfSummaries", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        TwinfieldApi.TwinfieldDeclarationsService.GetRangeOfSummariesResponse GetRangeOfSummaries(TwinfieldApi.TwinfieldDeclarationsService.GetRangeOfSummariesRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://www.twinfield.com/GetRangeOfSummaries", ReplyAction="*")]
        System.Threading.Tasks.Task<TwinfieldApi.TwinfieldDeclarationsService.GetRangeOfSummariesResponse> GetRangeOfSummariesAsync(TwinfieldApi.TwinfieldDeclarationsService.GetRangeOfSummariesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.twinfield.com/GetNumberOfDeclarations", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        TwinfieldApi.TwinfieldDeclarationsService.GetNumberOfDeclarationsResponse GetNumberOfDeclarations(TwinfieldApi.TwinfieldDeclarationsService.GetNumberOfDeclarationsRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://www.twinfield.com/GetNumberOfDeclarations", ReplyAction="*")]
        System.Threading.Tasks.Task<TwinfieldApi.TwinfieldDeclarationsService.GetNumberOfDeclarationsResponse> GetNumberOfDeclarationsAsync(TwinfieldApi.TwinfieldDeclarationsService.GetNumberOfDeclarationsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.twinfield.com/GetVatReturnAsXbrl", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        TwinfieldApi.TwinfieldDeclarationsService.GetVatReturnAsXbrlResponse GetVatReturnAsXbrl(TwinfieldApi.TwinfieldDeclarationsService.GetVatReturnAsXbrlRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://www.twinfield.com/GetVatReturnAsXbrl", ReplyAction="*")]
        System.Threading.Tasks.Task<TwinfieldApi.TwinfieldDeclarationsService.GetVatReturnAsXbrlResponse> GetVatReturnAsXbrlAsync(TwinfieldApi.TwinfieldDeclarationsService.GetVatReturnAsXbrlRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.twinfield.com/GetVatReturnAsXml", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        TwinfieldApi.TwinfieldDeclarationsService.GetVatReturnAsXmlResponse GetVatReturnAsXml(TwinfieldApi.TwinfieldDeclarationsService.GetVatReturnAsXmlRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://www.twinfield.com/GetVatReturnAsXml", ReplyAction="*")]
        System.Threading.Tasks.Task<TwinfieldApi.TwinfieldDeclarationsService.GetVatReturnAsXmlResponse> GetVatReturnAsXmlAsync(TwinfieldApi.TwinfieldDeclarationsService.GetVatReturnAsXmlRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.twinfield.com/GetVatReturnPaymentReference", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        TwinfieldApi.TwinfieldDeclarationsService.GetVatReturnPaymentReferenceResponse GetVatReturnPaymentReference(TwinfieldApi.TwinfieldDeclarationsService.GetVatReturnPaymentReferenceRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://www.twinfield.com/GetVatReturnPaymentReference", ReplyAction="*")]
        System.Threading.Tasks.Task<TwinfieldApi.TwinfieldDeclarationsService.GetVatReturnPaymentReferenceResponse> GetVatReturnPaymentReferenceAsync(TwinfieldApi.TwinfieldDeclarationsService.GetVatReturnPaymentReferenceRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.twinfield.com/GetIctReturnAsXbrl", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        TwinfieldApi.TwinfieldDeclarationsService.GetIctReturnAsXbrlResponse GetIctReturnAsXbrl(TwinfieldApi.TwinfieldDeclarationsService.GetIctReturnAsXbrlRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://www.twinfield.com/GetIctReturnAsXbrl", ReplyAction="*")]
        System.Threading.Tasks.Task<TwinfieldApi.TwinfieldDeclarationsService.GetIctReturnAsXbrlResponse> GetIctReturnAsXbrlAsync(TwinfieldApi.TwinfieldDeclarationsService.GetIctReturnAsXbrlRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.twinfield.com/GetIctReturnAsXml", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        TwinfieldApi.TwinfieldDeclarationsService.GetIctReturnAsXmlResponse GetIctReturnAsXml(TwinfieldApi.TwinfieldDeclarationsService.GetIctReturnAsXmlRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://www.twinfield.com/GetIctReturnAsXml", ReplyAction="*")]
        System.Threading.Tasks.Task<TwinfieldApi.TwinfieldDeclarationsService.GetIctReturnAsXmlResponse> GetIctReturnAsXmlAsync(TwinfieldApi.TwinfieldDeclarationsService.GetIctReturnAsXmlRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.twinfield.com/GetTaxGroupVatReturnAsXbrl", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        TwinfieldApi.TwinfieldDeclarationsService.GetTaxGroupVatReturnAsXbrlResponse GetTaxGroupVatReturnAsXbrl(TwinfieldApi.TwinfieldDeclarationsService.GetTaxGroupVatReturnAsXbrlRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://www.twinfield.com/GetTaxGroupVatReturnAsXbrl", ReplyAction="*")]
        System.Threading.Tasks.Task<TwinfieldApi.TwinfieldDeclarationsService.GetTaxGroupVatReturnAsXbrlResponse> GetTaxGroupVatReturnAsXbrlAsync(TwinfieldApi.TwinfieldDeclarationsService.GetTaxGroupVatReturnAsXbrlRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.twinfield.com/GetTaxGroupVatReturnAsXml", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        TwinfieldApi.TwinfieldDeclarationsService.GetTaxGroupVatReturnAsXmlResponse GetTaxGroupVatReturnAsXml(TwinfieldApi.TwinfieldDeclarationsService.GetTaxGroupVatReturnAsXmlRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://www.twinfield.com/GetTaxGroupVatReturnAsXml", ReplyAction="*")]
        System.Threading.Tasks.Task<TwinfieldApi.TwinfieldDeclarationsService.GetTaxGroupVatReturnAsXmlResponse> GetTaxGroupVatReturnAsXmlAsync(TwinfieldApi.TwinfieldDeclarationsService.GetTaxGroupVatReturnAsXmlRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.twinfield.com/GetTaxGroupVatReturnPaymentReference", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        TwinfieldApi.TwinfieldDeclarationsService.GetTaxGroupVatReturnPaymentReferenceResponse GetTaxGroupVatReturnPaymentReference(TwinfieldApi.TwinfieldDeclarationsService.GetTaxGroupVatReturnPaymentReferenceRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://www.twinfield.com/GetTaxGroupVatReturnPaymentReference", ReplyAction="*")]
        System.Threading.Tasks.Task<TwinfieldApi.TwinfieldDeclarationsService.GetTaxGroupVatReturnPaymentReferenceResponse> GetTaxGroupVatReturnPaymentReferenceAsync(TwinfieldApi.TwinfieldDeclarationsService.GetTaxGroupVatReturnPaymentReferenceRequest request);
        
        // CODEGEN: Generating message contract since message SetToSentRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="http://www.twinfield.com/SetToSent", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        TwinfieldApi.TwinfieldDeclarationsService.SetToSentResponse SetToSent(TwinfieldApi.TwinfieldDeclarationsService.SetToSentRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.twinfield.com/SetToSent", ReplyAction="*")]
        System.Threading.Tasks.Task<TwinfieldApi.TwinfieldDeclarationsService.SetToSentResponse> SetToSentAsync(TwinfieldApi.TwinfieldDeclarationsService.SetToSentRequest request);
        
        // CODEGEN: Generating message contract since message SetToApprovedRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="http://www.twinfield.com/SetToApproved", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        TwinfieldApi.TwinfieldDeclarationsService.SetToApprovedResponse SetToApproved(TwinfieldApi.TwinfieldDeclarationsService.SetToApprovedRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.twinfield.com/SetToApproved", ReplyAction="*")]
        System.Threading.Tasks.Task<TwinfieldApi.TwinfieldDeclarationsService.SetToApprovedResponse> SetToApprovedAsync(TwinfieldApi.TwinfieldDeclarationsService.SetToApprovedRequest request);
        
        // CODEGEN: Generating message contract since message SetToRejectedRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="http://www.twinfield.com/SetToRejected", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        TwinfieldApi.TwinfieldDeclarationsService.SetToRejectedResponse SetToRejected(TwinfieldApi.TwinfieldDeclarationsService.SetToRejectedRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.twinfield.com/SetToRejected", ReplyAction="*")]
        System.Threading.Tasks.Task<TwinfieldApi.TwinfieldDeclarationsService.SetToRejectedResponse> SetToRejectedAsync(TwinfieldApi.TwinfieldDeclarationsService.SetToRejectedRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.twinfield.com/")]
    public partial class Header : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string sessionIDField;
        
        private string accessTokenField;
        
        private string companyCodeField;
        
        private System.Nullable<System.Guid> companyIdField;
        
        private System.Xml.XmlAttribute[] anyAttrField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string SessionID {
            get {
                return this.sessionIDField;
            }
            set {
                this.sessionIDField = value;
                this.RaisePropertyChanged("SessionID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string AccessToken {
            get {
                return this.accessTokenField;
            }
            set {
                this.accessTokenField = value;
                this.RaisePropertyChanged("AccessToken");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string CompanyCode {
            get {
                return this.companyCodeField;
            }
            set {
                this.companyCodeField = value;
                this.RaisePropertyChanged("CompanyCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=3)]
        public System.Nullable<System.Guid> CompanyId {
            get {
                return this.companyIdField;
            }
            set {
                this.companyIdField = value;
                this.RaisePropertyChanged("CompanyId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyAttributeAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr {
            get {
                return this.anyAttrField;
            }
            set {
                this.anyAttrField = value;
                this.RaisePropertyChanged("AnyAttr");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.twinfield.com/")]
    public partial class MessageOfSetStatusMessages : object, System.ComponentModel.INotifyPropertyChanged {
        
        private MessageType typeField;
        
        private string textField;
        
        private SetStatusMessages codeField;
        
        private string[] parametersField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public MessageType Type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
                this.RaisePropertyChanged("Type");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Text {
            get {
                return this.textField;
            }
            set {
                this.textField = value;
                this.RaisePropertyChanged("Text");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public SetStatusMessages Code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
                this.RaisePropertyChanged("Code");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=3)]
        public string[] Parameters {
            get {
                return this.parametersField;
            }
            set {
                this.parametersField = value;
                this.RaisePropertyChanged("Parameters");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.twinfield.com/")]
    public enum MessageType {
        
        /// <remarks/>
        Error,
        
        /// <remarks/>
        Warning,
        
        /// <remarks/>
        Informational,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.twinfield.com/")]
    public enum SetStatusMessages {
        
        /// <remarks/>
        NoAccess,
        
        /// <remarks/>
        DocumentDoesNotExist,
        
        /// <remarks/>
        StartStatusInCorrectForTransition,
        
        /// <remarks/>
        UnableToPerformTransition,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.twinfield.com/")]
    public partial class CodeName : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string codeField;
        
        private string nameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
                this.RaisePropertyChanged("Code");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("Name");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.twinfield.com/")]
    public partial class DocumentStatus : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string descriptionField;
        
        private int stepIndexField;
        
        private string extraInformationField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
                this.RaisePropertyChanged("Description");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int StepIndex {
            get {
                return this.stepIndexField;
            }
            set {
                this.stepIndexField = value;
                this.RaisePropertyChanged("StepIndex");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string ExtraInformation {
            get {
                return this.extraInformationField;
            }
            set {
                this.extraInformationField = value;
                this.RaisePropertyChanged("ExtraInformation");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.twinfield.com/")]
    public partial class DocumentTimeFrame : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int yearField;
        
        private string periodField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int Year {
            get {
                return this.yearField;
            }
            set {
                this.yearField = value;
                this.RaisePropertyChanged("Year");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Period {
            get {
                return this.periodField;
            }
            set {
                this.periodField = value;
                this.RaisePropertyChanged("Period");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.twinfield.com/")]
    public partial class DeclarationSummary : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int idField;
        
        private string documentCodeField;
        
        private string nameField;
        
        private DocumentTimeFrame documentTimeFrameField;
        
        private DocumentStatus statusField;
        
        private CodeName assigneeField;
        
        private CodeName companyField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("Id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string DocumentCode {
            get {
                return this.documentCodeField;
            }
            set {
                this.documentCodeField = value;
                this.RaisePropertyChanged("DocumentCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("Name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public DocumentTimeFrame DocumentTimeFrame {
            get {
                return this.documentTimeFrameField;
            }
            set {
                this.documentTimeFrameField = value;
                this.RaisePropertyChanged("DocumentTimeFrame");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public DocumentStatus Status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
                this.RaisePropertyChanged("Status");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public CodeName Assignee {
            get {
                return this.assigneeField;
            }
            set {
                this.assigneeField = value;
                this.RaisePropertyChanged("Assignee");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public CodeName Company {
            get {
                return this.companyField;
            }
            set {
                this.companyField = value;
                this.RaisePropertyChanged("Company");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.twinfield.com/")]
    public partial class MessageOfLoadMessage : object, System.ComponentModel.INotifyPropertyChanged {
        
        private MessageType typeField;
        
        private string textField;
        
        private LoadMessage codeField;
        
        private string[] parametersField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public MessageType Type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
                this.RaisePropertyChanged("Type");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Text {
            get {
                return this.textField;
            }
            set {
                this.textField = value;
                this.RaisePropertyChanged("Text");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public LoadMessage Code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
                this.RaisePropertyChanged("Code");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=3)]
        public string[] Parameters {
            get {
                return this.parametersField;
            }
            set {
                this.parametersField = value;
                this.RaisePropertyChanged("Parameters");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.twinfield.com/")]
    public enum LoadMessage {
        
        /// <remarks/>
        NoAccess,
        
        /// <remarks/>
        InvalidCode,
        
        /// <remarks/>
        InvalidParameter,
        
        /// <remarks/>
        NotSupported,
        
        /// <remarks/>
        InvalidDocumentType,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetAllSummaries", WrapperNamespace="http://www.twinfield.com/", IsWrapped=true)]
    public partial class GetAllSummariesRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://www.twinfield.com/")]
        public TwinfieldApi.TwinfieldDeclarationsService.Header Header;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.twinfield.com/", Order=0)]
        public string companyCode;
        
        public GetAllSummariesRequest() {
        }
        
        public GetAllSummariesRequest(TwinfieldApi.TwinfieldDeclarationsService.Header Header, string companyCode) {
            this.Header = Header;
            this.companyCode = companyCode;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetAllSummariesResponse", WrapperNamespace="http://www.twinfield.com/", IsWrapped=true)]
    public partial class GetAllSummariesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.twinfield.com/", Order=0)]
        public TwinfieldApi.TwinfieldDeclarationsService.MessageOfLoadMessage[] GetAllSummariesResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.twinfield.com/", Order=1)]
        public TwinfieldApi.TwinfieldDeclarationsService.DeclarationSummary[] vatReturn;
        
        public GetAllSummariesResponse() {
        }
        
        public GetAllSummariesResponse(TwinfieldApi.TwinfieldDeclarationsService.MessageOfLoadMessage[] GetAllSummariesResult, TwinfieldApi.TwinfieldDeclarationsService.DeclarationSummary[] vatReturn) {
            this.GetAllSummariesResult = GetAllSummariesResult;
            this.vatReturn = vatReturn;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetRangeOfSummaries", WrapperNamespace="http://www.twinfield.com/", IsWrapped=true)]
    public partial class GetRangeOfSummariesRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://www.twinfield.com/")]
        public TwinfieldApi.TwinfieldDeclarationsService.Header Header;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.twinfield.com/", Order=0)]
        public string companyCode;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.twinfield.com/", Order=1)]
        public int startIndex;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.twinfield.com/", Order=2)]
        public int count;
        
        public GetRangeOfSummariesRequest() {
        }
        
        public GetRangeOfSummariesRequest(TwinfieldApi.TwinfieldDeclarationsService.Header Header, string companyCode, int startIndex, int count) {
            this.Header = Header;
            this.companyCode = companyCode;
            this.startIndex = startIndex;
            this.count = count;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetRangeOfSummariesResponse", WrapperNamespace="http://www.twinfield.com/", IsWrapped=true)]
    public partial class GetRangeOfSummariesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.twinfield.com/", Order=0)]
        public TwinfieldApi.TwinfieldDeclarationsService.MessageOfLoadMessage[] GetRangeOfSummariesResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.twinfield.com/", Order=1)]
        public TwinfieldApi.TwinfieldDeclarationsService.DeclarationSummary[] vatReturn;
        
        public GetRangeOfSummariesResponse() {
        }
        
        public GetRangeOfSummariesResponse(TwinfieldApi.TwinfieldDeclarationsService.MessageOfLoadMessage[] GetRangeOfSummariesResult, TwinfieldApi.TwinfieldDeclarationsService.DeclarationSummary[] vatReturn) {
            this.GetRangeOfSummariesResult = GetRangeOfSummariesResult;
            this.vatReturn = vatReturn;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetNumberOfDeclarations", WrapperNamespace="http://www.twinfield.com/", IsWrapped=true)]
    public partial class GetNumberOfDeclarationsRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://www.twinfield.com/")]
        public TwinfieldApi.TwinfieldDeclarationsService.Header Header;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.twinfield.com/", Order=0)]
        public string companyCode;
        
        public GetNumberOfDeclarationsRequest() {
        }
        
        public GetNumberOfDeclarationsRequest(TwinfieldApi.TwinfieldDeclarationsService.Header Header, string companyCode) {
            this.Header = Header;
            this.companyCode = companyCode;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetNumberOfDeclarationsResponse", WrapperNamespace="http://www.twinfield.com/", IsWrapped=true)]
    public partial class GetNumberOfDeclarationsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.twinfield.com/", Order=0)]
        public TwinfieldApi.TwinfieldDeclarationsService.MessageOfLoadMessage[] GetNumberOfDeclarationsResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.twinfield.com/", Order=1)]
        public int numberOfVatReturns;
        
        public GetNumberOfDeclarationsResponse() {
        }
        
        public GetNumberOfDeclarationsResponse(TwinfieldApi.TwinfieldDeclarationsService.MessageOfLoadMessage[] GetNumberOfDeclarationsResult, int numberOfVatReturns) {
            this.GetNumberOfDeclarationsResult = GetNumberOfDeclarationsResult;
            this.numberOfVatReturns = numberOfVatReturns;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetVatReturnAsXbrl", WrapperNamespace="http://www.twinfield.com/", IsWrapped=true)]
    public partial class GetVatReturnAsXbrlRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://www.twinfield.com/")]
        public TwinfieldApi.TwinfieldDeclarationsService.Header Header;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.twinfield.com/", Order=0)]
        public int documentId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.twinfield.com/", Order=1)]
        public bool isMessageIdRequired;
        
        public GetVatReturnAsXbrlRequest() {
        }
        
        public GetVatReturnAsXbrlRequest(TwinfieldApi.TwinfieldDeclarationsService.Header Header, int documentId, bool isMessageIdRequired) {
            this.Header = Header;
            this.documentId = documentId;
            this.isMessageIdRequired = isMessageIdRequired;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetVatReturnAsXbrlResponse", WrapperNamespace="http://www.twinfield.com/", IsWrapped=true)]
    public partial class GetVatReturnAsXbrlResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.twinfield.com/", Order=0)]
        public TwinfieldApi.TwinfieldDeclarationsService.MessageOfLoadMessage[] GetVatReturnAsXbrlResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.twinfield.com/", Order=1)]
        public System.Xml.XmlNode vatReturn;
        
        public GetVatReturnAsXbrlResponse() {
        }
        
        public GetVatReturnAsXbrlResponse(TwinfieldApi.TwinfieldDeclarationsService.MessageOfLoadMessage[] GetVatReturnAsXbrlResult, System.Xml.XmlNode vatReturn) {
            this.GetVatReturnAsXbrlResult = GetVatReturnAsXbrlResult;
            this.vatReturn = vatReturn;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetVatReturnAsXml", WrapperNamespace="http://www.twinfield.com/", IsWrapped=true)]
    public partial class GetVatReturnAsXmlRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://www.twinfield.com/")]
        public TwinfieldApi.TwinfieldDeclarationsService.Header Header;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.twinfield.com/", Order=0)]
        public int documentId;
        
        public GetVatReturnAsXmlRequest() {
        }
        
        public GetVatReturnAsXmlRequest(TwinfieldApi.TwinfieldDeclarationsService.Header Header, int documentId) {
            this.Header = Header;
            this.documentId = documentId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetVatReturnAsXmlResponse", WrapperNamespace="http://www.twinfield.com/", IsWrapped=true)]
    public partial class GetVatReturnAsXmlResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.twinfield.com/", Order=0)]
        public TwinfieldApi.TwinfieldDeclarationsService.MessageOfLoadMessage[] GetVatReturnAsXmlResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.twinfield.com/", Order=1)]
        public System.Xml.XmlNode vatReturn;
        
        public GetVatReturnAsXmlResponse() {
        }
        
        public GetVatReturnAsXmlResponse(TwinfieldApi.TwinfieldDeclarationsService.MessageOfLoadMessage[] GetVatReturnAsXmlResult, System.Xml.XmlNode vatReturn) {
            this.GetVatReturnAsXmlResult = GetVatReturnAsXmlResult;
            this.vatReturn = vatReturn;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetVatReturnPaymentReference", WrapperNamespace="http://www.twinfield.com/", IsWrapped=true)]
    public partial class GetVatReturnPaymentReferenceRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://www.twinfield.com/")]
        public TwinfieldApi.TwinfieldDeclarationsService.Header Header;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.twinfield.com/", Order=0)]
        public int documentId;
        
        public GetVatReturnPaymentReferenceRequest() {
        }
        
        public GetVatReturnPaymentReferenceRequest(TwinfieldApi.TwinfieldDeclarationsService.Header Header, int documentId) {
            this.Header = Header;
            this.documentId = documentId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetVatReturnPaymentReferenceResponse", WrapperNamespace="http://www.twinfield.com/", IsWrapped=true)]
    public partial class GetVatReturnPaymentReferenceResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.twinfield.com/", Order=0)]
        public TwinfieldApi.TwinfieldDeclarationsService.MessageOfLoadMessage[] GetVatReturnPaymentReferenceResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.twinfield.com/", Order=1)]
        public string paymentReference;
        
        public GetVatReturnPaymentReferenceResponse() {
        }
        
        public GetVatReturnPaymentReferenceResponse(TwinfieldApi.TwinfieldDeclarationsService.MessageOfLoadMessage[] GetVatReturnPaymentReferenceResult, string paymentReference) {
            this.GetVatReturnPaymentReferenceResult = GetVatReturnPaymentReferenceResult;
            this.paymentReference = paymentReference;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetIctReturnAsXbrl", WrapperNamespace="http://www.twinfield.com/", IsWrapped=true)]
    public partial class GetIctReturnAsXbrlRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://www.twinfield.com/")]
        public TwinfieldApi.TwinfieldDeclarationsService.Header Header;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.twinfield.com/", Order=0)]
        public int documentId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.twinfield.com/", Order=1)]
        public bool isMessageIdRequired;
        
        public GetIctReturnAsXbrlRequest() {
        }
        
        public GetIctReturnAsXbrlRequest(TwinfieldApi.TwinfieldDeclarationsService.Header Header, int documentId, bool isMessageIdRequired) {
            this.Header = Header;
            this.documentId = documentId;
            this.isMessageIdRequired = isMessageIdRequired;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetIctReturnAsXbrlResponse", WrapperNamespace="http://www.twinfield.com/", IsWrapped=true)]
    public partial class GetIctReturnAsXbrlResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.twinfield.com/", Order=0)]
        public TwinfieldApi.TwinfieldDeclarationsService.MessageOfLoadMessage[] GetIctReturnAsXbrlResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.twinfield.com/", Order=1)]
        public System.Xml.XmlNode vatReturn;
        
        public GetIctReturnAsXbrlResponse() {
        }
        
        public GetIctReturnAsXbrlResponse(TwinfieldApi.TwinfieldDeclarationsService.MessageOfLoadMessage[] GetIctReturnAsXbrlResult, System.Xml.XmlNode vatReturn) {
            this.GetIctReturnAsXbrlResult = GetIctReturnAsXbrlResult;
            this.vatReturn = vatReturn;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetIctReturnAsXml", WrapperNamespace="http://www.twinfield.com/", IsWrapped=true)]
    public partial class GetIctReturnAsXmlRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://www.twinfield.com/")]
        public TwinfieldApi.TwinfieldDeclarationsService.Header Header;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.twinfield.com/", Order=0)]
        public int documentId;
        
        public GetIctReturnAsXmlRequest() {
        }
        
        public GetIctReturnAsXmlRequest(TwinfieldApi.TwinfieldDeclarationsService.Header Header, int documentId) {
            this.Header = Header;
            this.documentId = documentId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetIctReturnAsXmlResponse", WrapperNamespace="http://www.twinfield.com/", IsWrapped=true)]
    public partial class GetIctReturnAsXmlResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.twinfield.com/", Order=0)]
        public TwinfieldApi.TwinfieldDeclarationsService.MessageOfLoadMessage[] GetIctReturnAsXmlResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.twinfield.com/", Order=1)]
        public System.Xml.XmlNode vatReturn;
        
        public GetIctReturnAsXmlResponse() {
        }
        
        public GetIctReturnAsXmlResponse(TwinfieldApi.TwinfieldDeclarationsService.MessageOfLoadMessage[] GetIctReturnAsXmlResult, System.Xml.XmlNode vatReturn) {
            this.GetIctReturnAsXmlResult = GetIctReturnAsXmlResult;
            this.vatReturn = vatReturn;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetTaxGroupVatReturnAsXbrl", WrapperNamespace="http://www.twinfield.com/", IsWrapped=true)]
    public partial class GetTaxGroupVatReturnAsXbrlRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://www.twinfield.com/")]
        public TwinfieldApi.TwinfieldDeclarationsService.Header Header;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.twinfield.com/", Order=0)]
        public int documentId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.twinfield.com/", Order=1)]
        public bool isMessageIdRequired;
        
        public GetTaxGroupVatReturnAsXbrlRequest() {
        }
        
        public GetTaxGroupVatReturnAsXbrlRequest(TwinfieldApi.TwinfieldDeclarationsService.Header Header, int documentId, bool isMessageIdRequired) {
            this.Header = Header;
            this.documentId = documentId;
            this.isMessageIdRequired = isMessageIdRequired;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetTaxGroupVatReturnAsXbrlResponse", WrapperNamespace="http://www.twinfield.com/", IsWrapped=true)]
    public partial class GetTaxGroupVatReturnAsXbrlResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.twinfield.com/", Order=0)]
        public TwinfieldApi.TwinfieldDeclarationsService.MessageOfLoadMessage[] GetTaxGroupVatReturnAsXbrlResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.twinfield.com/", Order=1)]
        public System.Xml.XmlNode vatReturn;
        
        public GetTaxGroupVatReturnAsXbrlResponse() {
        }
        
        public GetTaxGroupVatReturnAsXbrlResponse(TwinfieldApi.TwinfieldDeclarationsService.MessageOfLoadMessage[] GetTaxGroupVatReturnAsXbrlResult, System.Xml.XmlNode vatReturn) {
            this.GetTaxGroupVatReturnAsXbrlResult = GetTaxGroupVatReturnAsXbrlResult;
            this.vatReturn = vatReturn;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetTaxGroupVatReturnAsXml", WrapperNamespace="http://www.twinfield.com/", IsWrapped=true)]
    public partial class GetTaxGroupVatReturnAsXmlRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://www.twinfield.com/")]
        public TwinfieldApi.TwinfieldDeclarationsService.Header Header;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.twinfield.com/", Order=0)]
        public int documentId;
        
        public GetTaxGroupVatReturnAsXmlRequest() {
        }
        
        public GetTaxGroupVatReturnAsXmlRequest(TwinfieldApi.TwinfieldDeclarationsService.Header Header, int documentId) {
            this.Header = Header;
            this.documentId = documentId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetTaxGroupVatReturnAsXmlResponse", WrapperNamespace="http://www.twinfield.com/", IsWrapped=true)]
    public partial class GetTaxGroupVatReturnAsXmlResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.twinfield.com/", Order=0)]
        public TwinfieldApi.TwinfieldDeclarationsService.MessageOfLoadMessage[] GetTaxGroupVatReturnAsXmlResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.twinfield.com/", Order=1)]
        public System.Xml.XmlNode vatReturn;
        
        public GetTaxGroupVatReturnAsXmlResponse() {
        }
        
        public GetTaxGroupVatReturnAsXmlResponse(TwinfieldApi.TwinfieldDeclarationsService.MessageOfLoadMessage[] GetTaxGroupVatReturnAsXmlResult, System.Xml.XmlNode vatReturn) {
            this.GetTaxGroupVatReturnAsXmlResult = GetTaxGroupVatReturnAsXmlResult;
            this.vatReturn = vatReturn;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetTaxGroupVatReturnPaymentReference", WrapperNamespace="http://www.twinfield.com/", IsWrapped=true)]
    public partial class GetTaxGroupVatReturnPaymentReferenceRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://www.twinfield.com/")]
        public TwinfieldApi.TwinfieldDeclarationsService.Header Header;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.twinfield.com/", Order=0)]
        public int documentId;
        
        public GetTaxGroupVatReturnPaymentReferenceRequest() {
        }
        
        public GetTaxGroupVatReturnPaymentReferenceRequest(TwinfieldApi.TwinfieldDeclarationsService.Header Header, int documentId) {
            this.Header = Header;
            this.documentId = documentId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetTaxGroupVatReturnPaymentReferenceResponse", WrapperNamespace="http://www.twinfield.com/", IsWrapped=true)]
    public partial class GetTaxGroupVatReturnPaymentReferenceResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.twinfield.com/", Order=0)]
        public TwinfieldApi.TwinfieldDeclarationsService.MessageOfLoadMessage[] GetTaxGroupVatReturnPaymentReferenceResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.twinfield.com/", Order=1)]
        public string paymentReference;
        
        public GetTaxGroupVatReturnPaymentReferenceResponse() {
        }
        
        public GetTaxGroupVatReturnPaymentReferenceResponse(TwinfieldApi.TwinfieldDeclarationsService.MessageOfLoadMessage[] GetTaxGroupVatReturnPaymentReferenceResult, string paymentReference) {
            this.GetTaxGroupVatReturnPaymentReferenceResult = GetTaxGroupVatReturnPaymentReferenceResult;
            this.paymentReference = paymentReference;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SetToSent", WrapperNamespace="http://www.twinfield.com/", IsWrapped=true)]
    public partial class SetToSentRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://www.twinfield.com/")]
        public TwinfieldApi.TwinfieldDeclarationsService.Header Header;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.twinfield.com/", Order=0)]
        public int documentId;
        
        public SetToSentRequest() {
        }
        
        public SetToSentRequest(TwinfieldApi.TwinfieldDeclarationsService.Header Header, int documentId) {
            this.Header = Header;
            this.documentId = documentId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SetToSentResponse", WrapperNamespace="http://www.twinfield.com/", IsWrapped=true)]
    public partial class SetToSentResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.twinfield.com/", Order=0)]
        public TwinfieldApi.TwinfieldDeclarationsService.MessageOfSetStatusMessages[] SetToSentResult;
        
        public SetToSentResponse() {
        }
        
        public SetToSentResponse(TwinfieldApi.TwinfieldDeclarationsService.MessageOfSetStatusMessages[] SetToSentResult) {
            this.SetToSentResult = SetToSentResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SetToApproved", WrapperNamespace="http://www.twinfield.com/", IsWrapped=true)]
    public partial class SetToApprovedRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://www.twinfield.com/")]
        public TwinfieldApi.TwinfieldDeclarationsService.Header Header;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.twinfield.com/", Order=0)]
        public int documentId;
        
        public SetToApprovedRequest() {
        }
        
        public SetToApprovedRequest(TwinfieldApi.TwinfieldDeclarationsService.Header Header, int documentId) {
            this.Header = Header;
            this.documentId = documentId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SetToApprovedResponse", WrapperNamespace="http://www.twinfield.com/", IsWrapped=true)]
    public partial class SetToApprovedResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.twinfield.com/", Order=0)]
        public TwinfieldApi.TwinfieldDeclarationsService.MessageOfSetStatusMessages[] SetToApprovedResult;
        
        public SetToApprovedResponse() {
        }
        
        public SetToApprovedResponse(TwinfieldApi.TwinfieldDeclarationsService.MessageOfSetStatusMessages[] SetToApprovedResult) {
            this.SetToApprovedResult = SetToApprovedResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SetToRejected", WrapperNamespace="http://www.twinfield.com/", IsWrapped=true)]
    public partial class SetToRejectedRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://www.twinfield.com/")]
        public TwinfieldApi.TwinfieldDeclarationsService.Header Header;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.twinfield.com/", Order=0)]
        public int documentId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.twinfield.com/", Order=1)]
        public string reason;
        
        public SetToRejectedRequest() {
        }
        
        public SetToRejectedRequest(TwinfieldApi.TwinfieldDeclarationsService.Header Header, int documentId, string reason) {
            this.Header = Header;
            this.documentId = documentId;
            this.reason = reason;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SetToRejectedResponse", WrapperNamespace="http://www.twinfield.com/", IsWrapped=true)]
    public partial class SetToRejectedResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.twinfield.com/", Order=0)]
        public TwinfieldApi.TwinfieldDeclarationsService.MessageOfSetStatusMessages[] SetToRejectedResult;
        
        public SetToRejectedResponse() {
        }
        
        public SetToRejectedResponse(TwinfieldApi.TwinfieldDeclarationsService.MessageOfSetStatusMessages[] SetToRejectedResult) {
            this.SetToRejectedResult = SetToRejectedResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface DeclarationsSoapChannel : TwinfieldApi.TwinfieldDeclarationsService.DeclarationsSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DeclarationsSoapClient : System.ServiceModel.ClientBase<TwinfieldApi.TwinfieldDeclarationsService.DeclarationsSoap>, TwinfieldApi.TwinfieldDeclarationsService.DeclarationsSoap {
        
        public DeclarationsSoapClient() {
        }
        
        public DeclarationsSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public DeclarationsSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DeclarationsSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DeclarationsSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TwinfieldApi.TwinfieldDeclarationsService.GetAllSummariesResponse TwinfieldApi.TwinfieldDeclarationsService.DeclarationsSoap.GetAllSummaries(TwinfieldApi.TwinfieldDeclarationsService.GetAllSummariesRequest request) {
            return base.Channel.GetAllSummaries(request);
        }
        
        public TwinfieldApi.TwinfieldDeclarationsService.MessageOfLoadMessage[] GetAllSummaries(TwinfieldApi.TwinfieldDeclarationsService.Header Header, string companyCode, out TwinfieldApi.TwinfieldDeclarationsService.DeclarationSummary[] vatReturn) {
            TwinfieldApi.TwinfieldDeclarationsService.GetAllSummariesRequest inValue = new TwinfieldApi.TwinfieldDeclarationsService.GetAllSummariesRequest();
            inValue.Header = Header;
            inValue.companyCode = companyCode;
            TwinfieldApi.TwinfieldDeclarationsService.GetAllSummariesResponse retVal = ((TwinfieldApi.TwinfieldDeclarationsService.DeclarationsSoap)(this)).GetAllSummaries(inValue);
            vatReturn = retVal.vatReturn;
            return retVal.GetAllSummariesResult;
        }
        
        public System.Threading.Tasks.Task<TwinfieldApi.TwinfieldDeclarationsService.GetAllSummariesResponse> GetAllSummariesAsync(TwinfieldApi.TwinfieldDeclarationsService.GetAllSummariesRequest request) {
            return base.Channel.GetAllSummariesAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TwinfieldApi.TwinfieldDeclarationsService.GetRangeOfSummariesResponse TwinfieldApi.TwinfieldDeclarationsService.DeclarationsSoap.GetRangeOfSummaries(TwinfieldApi.TwinfieldDeclarationsService.GetRangeOfSummariesRequest request) {
            return base.Channel.GetRangeOfSummaries(request);
        }
        
        public TwinfieldApi.TwinfieldDeclarationsService.MessageOfLoadMessage[] GetRangeOfSummaries(TwinfieldApi.TwinfieldDeclarationsService.Header Header, string companyCode, int startIndex, int count, out TwinfieldApi.TwinfieldDeclarationsService.DeclarationSummary[] vatReturn) {
            TwinfieldApi.TwinfieldDeclarationsService.GetRangeOfSummariesRequest inValue = new TwinfieldApi.TwinfieldDeclarationsService.GetRangeOfSummariesRequest();
            inValue.Header = Header;
            inValue.companyCode = companyCode;
            inValue.startIndex = startIndex;
            inValue.count = count;
            TwinfieldApi.TwinfieldDeclarationsService.GetRangeOfSummariesResponse retVal = ((TwinfieldApi.TwinfieldDeclarationsService.DeclarationsSoap)(this)).GetRangeOfSummaries(inValue);
            vatReturn = retVal.vatReturn;
            return retVal.GetRangeOfSummariesResult;
        }
        
        public System.Threading.Tasks.Task<TwinfieldApi.TwinfieldDeclarationsService.GetRangeOfSummariesResponse> GetRangeOfSummariesAsync(TwinfieldApi.TwinfieldDeclarationsService.GetRangeOfSummariesRequest request) {
            return base.Channel.GetRangeOfSummariesAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TwinfieldApi.TwinfieldDeclarationsService.GetNumberOfDeclarationsResponse TwinfieldApi.TwinfieldDeclarationsService.DeclarationsSoap.GetNumberOfDeclarations(TwinfieldApi.TwinfieldDeclarationsService.GetNumberOfDeclarationsRequest request) {
            return base.Channel.GetNumberOfDeclarations(request);
        }
        
        public TwinfieldApi.TwinfieldDeclarationsService.MessageOfLoadMessage[] GetNumberOfDeclarations(TwinfieldApi.TwinfieldDeclarationsService.Header Header, string companyCode, out int numberOfVatReturns) {
            TwinfieldApi.TwinfieldDeclarationsService.GetNumberOfDeclarationsRequest inValue = new TwinfieldApi.TwinfieldDeclarationsService.GetNumberOfDeclarationsRequest();
            inValue.Header = Header;
            inValue.companyCode = companyCode;
            TwinfieldApi.TwinfieldDeclarationsService.GetNumberOfDeclarationsResponse retVal = ((TwinfieldApi.TwinfieldDeclarationsService.DeclarationsSoap)(this)).GetNumberOfDeclarations(inValue);
            numberOfVatReturns = retVal.numberOfVatReturns;
            return retVal.GetNumberOfDeclarationsResult;
        }
        
        public System.Threading.Tasks.Task<TwinfieldApi.TwinfieldDeclarationsService.GetNumberOfDeclarationsResponse> GetNumberOfDeclarationsAsync(TwinfieldApi.TwinfieldDeclarationsService.GetNumberOfDeclarationsRequest request) {
            return base.Channel.GetNumberOfDeclarationsAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TwinfieldApi.TwinfieldDeclarationsService.GetVatReturnAsXbrlResponse TwinfieldApi.TwinfieldDeclarationsService.DeclarationsSoap.GetVatReturnAsXbrl(TwinfieldApi.TwinfieldDeclarationsService.GetVatReturnAsXbrlRequest request) {
            return base.Channel.GetVatReturnAsXbrl(request);
        }
        
        public TwinfieldApi.TwinfieldDeclarationsService.MessageOfLoadMessage[] GetVatReturnAsXbrl(TwinfieldApi.TwinfieldDeclarationsService.Header Header, int documentId, bool isMessageIdRequired, out System.Xml.XmlNode vatReturn) {
            TwinfieldApi.TwinfieldDeclarationsService.GetVatReturnAsXbrlRequest inValue = new TwinfieldApi.TwinfieldDeclarationsService.GetVatReturnAsXbrlRequest();
            inValue.Header = Header;
            inValue.documentId = documentId;
            inValue.isMessageIdRequired = isMessageIdRequired;
            TwinfieldApi.TwinfieldDeclarationsService.GetVatReturnAsXbrlResponse retVal = ((TwinfieldApi.TwinfieldDeclarationsService.DeclarationsSoap)(this)).GetVatReturnAsXbrl(inValue);
            vatReturn = retVal.vatReturn;
            return retVal.GetVatReturnAsXbrlResult;
        }
        
        public System.Threading.Tasks.Task<TwinfieldApi.TwinfieldDeclarationsService.GetVatReturnAsXbrlResponse> GetVatReturnAsXbrlAsync(TwinfieldApi.TwinfieldDeclarationsService.GetVatReturnAsXbrlRequest request) {
            return base.Channel.GetVatReturnAsXbrlAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TwinfieldApi.TwinfieldDeclarationsService.GetVatReturnAsXmlResponse TwinfieldApi.TwinfieldDeclarationsService.DeclarationsSoap.GetVatReturnAsXml(TwinfieldApi.TwinfieldDeclarationsService.GetVatReturnAsXmlRequest request) {
            return base.Channel.GetVatReturnAsXml(request);
        }
        
        public TwinfieldApi.TwinfieldDeclarationsService.MessageOfLoadMessage[] GetVatReturnAsXml(TwinfieldApi.TwinfieldDeclarationsService.Header Header, int documentId, out System.Xml.XmlNode vatReturn) {
            TwinfieldApi.TwinfieldDeclarationsService.GetVatReturnAsXmlRequest inValue = new TwinfieldApi.TwinfieldDeclarationsService.GetVatReturnAsXmlRequest();
            inValue.Header = Header;
            inValue.documentId = documentId;
            TwinfieldApi.TwinfieldDeclarationsService.GetVatReturnAsXmlResponse retVal = ((TwinfieldApi.TwinfieldDeclarationsService.DeclarationsSoap)(this)).GetVatReturnAsXml(inValue);
            vatReturn = retVal.vatReturn;
            return retVal.GetVatReturnAsXmlResult;
        }
        
        public System.Threading.Tasks.Task<TwinfieldApi.TwinfieldDeclarationsService.GetVatReturnAsXmlResponse> GetVatReturnAsXmlAsync(TwinfieldApi.TwinfieldDeclarationsService.GetVatReturnAsXmlRequest request) {
            return base.Channel.GetVatReturnAsXmlAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TwinfieldApi.TwinfieldDeclarationsService.GetVatReturnPaymentReferenceResponse TwinfieldApi.TwinfieldDeclarationsService.DeclarationsSoap.GetVatReturnPaymentReference(TwinfieldApi.TwinfieldDeclarationsService.GetVatReturnPaymentReferenceRequest request) {
            return base.Channel.GetVatReturnPaymentReference(request);
        }
        
        public TwinfieldApi.TwinfieldDeclarationsService.MessageOfLoadMessage[] GetVatReturnPaymentReference(TwinfieldApi.TwinfieldDeclarationsService.Header Header, int documentId, out string paymentReference) {
            TwinfieldApi.TwinfieldDeclarationsService.GetVatReturnPaymentReferenceRequest inValue = new TwinfieldApi.TwinfieldDeclarationsService.GetVatReturnPaymentReferenceRequest();
            inValue.Header = Header;
            inValue.documentId = documentId;
            TwinfieldApi.TwinfieldDeclarationsService.GetVatReturnPaymentReferenceResponse retVal = ((TwinfieldApi.TwinfieldDeclarationsService.DeclarationsSoap)(this)).GetVatReturnPaymentReference(inValue);
            paymentReference = retVal.paymentReference;
            return retVal.GetVatReturnPaymentReferenceResult;
        }
        
        public System.Threading.Tasks.Task<TwinfieldApi.TwinfieldDeclarationsService.GetVatReturnPaymentReferenceResponse> GetVatReturnPaymentReferenceAsync(TwinfieldApi.TwinfieldDeclarationsService.GetVatReturnPaymentReferenceRequest request) {
            return base.Channel.GetVatReturnPaymentReferenceAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TwinfieldApi.TwinfieldDeclarationsService.GetIctReturnAsXbrlResponse TwinfieldApi.TwinfieldDeclarationsService.DeclarationsSoap.GetIctReturnAsXbrl(TwinfieldApi.TwinfieldDeclarationsService.GetIctReturnAsXbrlRequest request) {
            return base.Channel.GetIctReturnAsXbrl(request);
        }
        
        public TwinfieldApi.TwinfieldDeclarationsService.MessageOfLoadMessage[] GetIctReturnAsXbrl(TwinfieldApi.TwinfieldDeclarationsService.Header Header, int documentId, bool isMessageIdRequired, out System.Xml.XmlNode vatReturn) {
            TwinfieldApi.TwinfieldDeclarationsService.GetIctReturnAsXbrlRequest inValue = new TwinfieldApi.TwinfieldDeclarationsService.GetIctReturnAsXbrlRequest();
            inValue.Header = Header;
            inValue.documentId = documentId;
            inValue.isMessageIdRequired = isMessageIdRequired;
            TwinfieldApi.TwinfieldDeclarationsService.GetIctReturnAsXbrlResponse retVal = ((TwinfieldApi.TwinfieldDeclarationsService.DeclarationsSoap)(this)).GetIctReturnAsXbrl(inValue);
            vatReturn = retVal.vatReturn;
            return retVal.GetIctReturnAsXbrlResult;
        }
        
        public System.Threading.Tasks.Task<TwinfieldApi.TwinfieldDeclarationsService.GetIctReturnAsXbrlResponse> GetIctReturnAsXbrlAsync(TwinfieldApi.TwinfieldDeclarationsService.GetIctReturnAsXbrlRequest request) {
            return base.Channel.GetIctReturnAsXbrlAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TwinfieldApi.TwinfieldDeclarationsService.GetIctReturnAsXmlResponse TwinfieldApi.TwinfieldDeclarationsService.DeclarationsSoap.GetIctReturnAsXml(TwinfieldApi.TwinfieldDeclarationsService.GetIctReturnAsXmlRequest request) {
            return base.Channel.GetIctReturnAsXml(request);
        }
        
        public TwinfieldApi.TwinfieldDeclarationsService.MessageOfLoadMessage[] GetIctReturnAsXml(TwinfieldApi.TwinfieldDeclarationsService.Header Header, int documentId, out System.Xml.XmlNode vatReturn) {
            TwinfieldApi.TwinfieldDeclarationsService.GetIctReturnAsXmlRequest inValue = new TwinfieldApi.TwinfieldDeclarationsService.GetIctReturnAsXmlRequest();
            inValue.Header = Header;
            inValue.documentId = documentId;
            TwinfieldApi.TwinfieldDeclarationsService.GetIctReturnAsXmlResponse retVal = ((TwinfieldApi.TwinfieldDeclarationsService.DeclarationsSoap)(this)).GetIctReturnAsXml(inValue);
            vatReturn = retVal.vatReturn;
            return retVal.GetIctReturnAsXmlResult;
        }
        
        public System.Threading.Tasks.Task<TwinfieldApi.TwinfieldDeclarationsService.GetIctReturnAsXmlResponse> GetIctReturnAsXmlAsync(TwinfieldApi.TwinfieldDeclarationsService.GetIctReturnAsXmlRequest request) {
            return base.Channel.GetIctReturnAsXmlAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TwinfieldApi.TwinfieldDeclarationsService.GetTaxGroupVatReturnAsXbrlResponse TwinfieldApi.TwinfieldDeclarationsService.DeclarationsSoap.GetTaxGroupVatReturnAsXbrl(TwinfieldApi.TwinfieldDeclarationsService.GetTaxGroupVatReturnAsXbrlRequest request) {
            return base.Channel.GetTaxGroupVatReturnAsXbrl(request);
        }
        
        public TwinfieldApi.TwinfieldDeclarationsService.MessageOfLoadMessage[] GetTaxGroupVatReturnAsXbrl(TwinfieldApi.TwinfieldDeclarationsService.Header Header, int documentId, bool isMessageIdRequired, out System.Xml.XmlNode vatReturn) {
            TwinfieldApi.TwinfieldDeclarationsService.GetTaxGroupVatReturnAsXbrlRequest inValue = new TwinfieldApi.TwinfieldDeclarationsService.GetTaxGroupVatReturnAsXbrlRequest();
            inValue.Header = Header;
            inValue.documentId = documentId;
            inValue.isMessageIdRequired = isMessageIdRequired;
            TwinfieldApi.TwinfieldDeclarationsService.GetTaxGroupVatReturnAsXbrlResponse retVal = ((TwinfieldApi.TwinfieldDeclarationsService.DeclarationsSoap)(this)).GetTaxGroupVatReturnAsXbrl(inValue);
            vatReturn = retVal.vatReturn;
            return retVal.GetTaxGroupVatReturnAsXbrlResult;
        }
        
        public System.Threading.Tasks.Task<TwinfieldApi.TwinfieldDeclarationsService.GetTaxGroupVatReturnAsXbrlResponse> GetTaxGroupVatReturnAsXbrlAsync(TwinfieldApi.TwinfieldDeclarationsService.GetTaxGroupVatReturnAsXbrlRequest request) {
            return base.Channel.GetTaxGroupVatReturnAsXbrlAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TwinfieldApi.TwinfieldDeclarationsService.GetTaxGroupVatReturnAsXmlResponse TwinfieldApi.TwinfieldDeclarationsService.DeclarationsSoap.GetTaxGroupVatReturnAsXml(TwinfieldApi.TwinfieldDeclarationsService.GetTaxGroupVatReturnAsXmlRequest request) {
            return base.Channel.GetTaxGroupVatReturnAsXml(request);
        }
        
        public TwinfieldApi.TwinfieldDeclarationsService.MessageOfLoadMessage[] GetTaxGroupVatReturnAsXml(TwinfieldApi.TwinfieldDeclarationsService.Header Header, int documentId, out System.Xml.XmlNode vatReturn) {
            TwinfieldApi.TwinfieldDeclarationsService.GetTaxGroupVatReturnAsXmlRequest inValue = new TwinfieldApi.TwinfieldDeclarationsService.GetTaxGroupVatReturnAsXmlRequest();
            inValue.Header = Header;
            inValue.documentId = documentId;
            TwinfieldApi.TwinfieldDeclarationsService.GetTaxGroupVatReturnAsXmlResponse retVal = ((TwinfieldApi.TwinfieldDeclarationsService.DeclarationsSoap)(this)).GetTaxGroupVatReturnAsXml(inValue);
            vatReturn = retVal.vatReturn;
            return retVal.GetTaxGroupVatReturnAsXmlResult;
        }
        
        public System.Threading.Tasks.Task<TwinfieldApi.TwinfieldDeclarationsService.GetTaxGroupVatReturnAsXmlResponse> GetTaxGroupVatReturnAsXmlAsync(TwinfieldApi.TwinfieldDeclarationsService.GetTaxGroupVatReturnAsXmlRequest request) {
            return base.Channel.GetTaxGroupVatReturnAsXmlAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TwinfieldApi.TwinfieldDeclarationsService.GetTaxGroupVatReturnPaymentReferenceResponse TwinfieldApi.TwinfieldDeclarationsService.DeclarationsSoap.GetTaxGroupVatReturnPaymentReference(TwinfieldApi.TwinfieldDeclarationsService.GetTaxGroupVatReturnPaymentReferenceRequest request) {
            return base.Channel.GetTaxGroupVatReturnPaymentReference(request);
        }
        
        public TwinfieldApi.TwinfieldDeclarationsService.MessageOfLoadMessage[] GetTaxGroupVatReturnPaymentReference(TwinfieldApi.TwinfieldDeclarationsService.Header Header, int documentId, out string paymentReference) {
            TwinfieldApi.TwinfieldDeclarationsService.GetTaxGroupVatReturnPaymentReferenceRequest inValue = new TwinfieldApi.TwinfieldDeclarationsService.GetTaxGroupVatReturnPaymentReferenceRequest();
            inValue.Header = Header;
            inValue.documentId = documentId;
            TwinfieldApi.TwinfieldDeclarationsService.GetTaxGroupVatReturnPaymentReferenceResponse retVal = ((TwinfieldApi.TwinfieldDeclarationsService.DeclarationsSoap)(this)).GetTaxGroupVatReturnPaymentReference(inValue);
            paymentReference = retVal.paymentReference;
            return retVal.GetTaxGroupVatReturnPaymentReferenceResult;
        }
        
        public System.Threading.Tasks.Task<TwinfieldApi.TwinfieldDeclarationsService.GetTaxGroupVatReturnPaymentReferenceResponse> GetTaxGroupVatReturnPaymentReferenceAsync(TwinfieldApi.TwinfieldDeclarationsService.GetTaxGroupVatReturnPaymentReferenceRequest request) {
            return base.Channel.GetTaxGroupVatReturnPaymentReferenceAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TwinfieldApi.TwinfieldDeclarationsService.SetToSentResponse TwinfieldApi.TwinfieldDeclarationsService.DeclarationsSoap.SetToSent(TwinfieldApi.TwinfieldDeclarationsService.SetToSentRequest request) {
            return base.Channel.SetToSent(request);
        }
        
        public TwinfieldApi.TwinfieldDeclarationsService.MessageOfSetStatusMessages[] SetToSent(TwinfieldApi.TwinfieldDeclarationsService.Header Header, int documentId) {
            TwinfieldApi.TwinfieldDeclarationsService.SetToSentRequest inValue = new TwinfieldApi.TwinfieldDeclarationsService.SetToSentRequest();
            inValue.Header = Header;
            inValue.documentId = documentId;
            TwinfieldApi.TwinfieldDeclarationsService.SetToSentResponse retVal = ((TwinfieldApi.TwinfieldDeclarationsService.DeclarationsSoap)(this)).SetToSent(inValue);
            return retVal.SetToSentResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TwinfieldApi.TwinfieldDeclarationsService.SetToSentResponse> TwinfieldApi.TwinfieldDeclarationsService.DeclarationsSoap.SetToSentAsync(TwinfieldApi.TwinfieldDeclarationsService.SetToSentRequest request) {
            return base.Channel.SetToSentAsync(request);
        }
        
        public System.Threading.Tasks.Task<TwinfieldApi.TwinfieldDeclarationsService.SetToSentResponse> SetToSentAsync(TwinfieldApi.TwinfieldDeclarationsService.Header Header, int documentId) {
            TwinfieldApi.TwinfieldDeclarationsService.SetToSentRequest inValue = new TwinfieldApi.TwinfieldDeclarationsService.SetToSentRequest();
            inValue.Header = Header;
            inValue.documentId = documentId;
            return ((TwinfieldApi.TwinfieldDeclarationsService.DeclarationsSoap)(this)).SetToSentAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TwinfieldApi.TwinfieldDeclarationsService.SetToApprovedResponse TwinfieldApi.TwinfieldDeclarationsService.DeclarationsSoap.SetToApproved(TwinfieldApi.TwinfieldDeclarationsService.SetToApprovedRequest request) {
            return base.Channel.SetToApproved(request);
        }
        
        public TwinfieldApi.TwinfieldDeclarationsService.MessageOfSetStatusMessages[] SetToApproved(TwinfieldApi.TwinfieldDeclarationsService.Header Header, int documentId) {
            TwinfieldApi.TwinfieldDeclarationsService.SetToApprovedRequest inValue = new TwinfieldApi.TwinfieldDeclarationsService.SetToApprovedRequest();
            inValue.Header = Header;
            inValue.documentId = documentId;
            TwinfieldApi.TwinfieldDeclarationsService.SetToApprovedResponse retVal = ((TwinfieldApi.TwinfieldDeclarationsService.DeclarationsSoap)(this)).SetToApproved(inValue);
            return retVal.SetToApprovedResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TwinfieldApi.TwinfieldDeclarationsService.SetToApprovedResponse> TwinfieldApi.TwinfieldDeclarationsService.DeclarationsSoap.SetToApprovedAsync(TwinfieldApi.TwinfieldDeclarationsService.SetToApprovedRequest request) {
            return base.Channel.SetToApprovedAsync(request);
        }
        
        public System.Threading.Tasks.Task<TwinfieldApi.TwinfieldDeclarationsService.SetToApprovedResponse> SetToApprovedAsync(TwinfieldApi.TwinfieldDeclarationsService.Header Header, int documentId) {
            TwinfieldApi.TwinfieldDeclarationsService.SetToApprovedRequest inValue = new TwinfieldApi.TwinfieldDeclarationsService.SetToApprovedRequest();
            inValue.Header = Header;
            inValue.documentId = documentId;
            return ((TwinfieldApi.TwinfieldDeclarationsService.DeclarationsSoap)(this)).SetToApprovedAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TwinfieldApi.TwinfieldDeclarationsService.SetToRejectedResponse TwinfieldApi.TwinfieldDeclarationsService.DeclarationsSoap.SetToRejected(TwinfieldApi.TwinfieldDeclarationsService.SetToRejectedRequest request) {
            return base.Channel.SetToRejected(request);
        }
        
        public TwinfieldApi.TwinfieldDeclarationsService.MessageOfSetStatusMessages[] SetToRejected(TwinfieldApi.TwinfieldDeclarationsService.Header Header, int documentId, string reason) {
            TwinfieldApi.TwinfieldDeclarationsService.SetToRejectedRequest inValue = new TwinfieldApi.TwinfieldDeclarationsService.SetToRejectedRequest();
            inValue.Header = Header;
            inValue.documentId = documentId;
            inValue.reason = reason;
            TwinfieldApi.TwinfieldDeclarationsService.SetToRejectedResponse retVal = ((TwinfieldApi.TwinfieldDeclarationsService.DeclarationsSoap)(this)).SetToRejected(inValue);
            return retVal.SetToRejectedResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TwinfieldApi.TwinfieldDeclarationsService.SetToRejectedResponse> TwinfieldApi.TwinfieldDeclarationsService.DeclarationsSoap.SetToRejectedAsync(TwinfieldApi.TwinfieldDeclarationsService.SetToRejectedRequest request) {
            return base.Channel.SetToRejectedAsync(request);
        }
        
        public System.Threading.Tasks.Task<TwinfieldApi.TwinfieldDeclarationsService.SetToRejectedResponse> SetToRejectedAsync(TwinfieldApi.TwinfieldDeclarationsService.Header Header, int documentId, string reason) {
            TwinfieldApi.TwinfieldDeclarationsService.SetToRejectedRequest inValue = new TwinfieldApi.TwinfieldDeclarationsService.SetToRejectedRequest();
            inValue.Header = Header;
            inValue.documentId = documentId;
            inValue.reason = reason;
            return ((TwinfieldApi.TwinfieldDeclarationsService.DeclarationsSoap)(this)).SetToRejectedAsync(inValue);
        }

        public MessageOfLoadMessage[] GetAllSummaries(Header header, string companyCode)
        {
            TwinfieldApi.TwinfieldDeclarationsService.GetAllSummariesRequest inValue = new TwinfieldApi.TwinfieldDeclarationsService.GetAllSummariesRequest();
            inValue.Header = header;
            inValue.companyCode = companyCode;
            TwinfieldApi.TwinfieldDeclarationsService.GetAllSummariesResponse retVal = ((TwinfieldApi.TwinfieldDeclarationsService.DeclarationsSoap)(this)).GetAllSummaries(inValue);
            return retVal.GetAllSummariesResult;
        }
    }
}
