//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TwinfieldApi.TwinfieldBankStatementService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AuthenticationHeader", Namespace="http://schemas.datacontract.org/2004/07/Twinfield.WebServices.Shared")]
    [System.SerializableAttribute()]
    public partial class AuthenticationHeader : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AccessTokenField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CompanyCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.Guid> CompanyIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AccessToken {
            get {
                return this.AccessTokenField;
            }
            set {
                if ((object.ReferenceEquals(this.AccessTokenField, value) != true)) {
                    this.AccessTokenField = value;
                    this.RaisePropertyChanged("AccessToken");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CompanyCode {
            get {
                return this.CompanyCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.CompanyCodeField, value) != true)) {
                    this.CompanyCodeField = value;
                    this.RaisePropertyChanged("CompanyCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.Guid> CompanyId {
            get {
                return this.CompanyIdField;
            }
            set {
                if ((this.CompanyIdField.Equals(value) != true)) {
                    this.CompanyIdField = value;
                    this.RaisePropertyChanged("CompanyId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Command", Namespace="http://schemas.datacontract.org/2004/07/Twinfield.WebServices")]
    [System.SerializableAttribute()]
    public partial class Command : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SecurityFault", Namespace="http://schemas.datacontract.org/2004/07/Twinfield.WebServices")]
    [System.SerializableAttribute()]
    public partial class SecurityFault : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private TwinfieldApi.TwinfieldBankStatementService.SecurityFaultCode CodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public TwinfieldApi.TwinfieldBankStatementService.SecurityFaultCode Code {
            get {
                return this.CodeField;
            }
            set {
                if ((this.CodeField.Equals(value) != true)) {
                    this.CodeField = value;
                    this.RaisePropertyChanged("Code");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SecurityFaultCode", Namespace="http://schemas.datacontract.org/2004/07/Twinfield.WebServices")]
    public enum SecurityFaultCode : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Unexpected = 100,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        HeaderIsMissing = 101,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        AccessDenied = 102,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        LogonInvalid = 103,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        LogonDeleted = 104,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        LogonDisabled = 105,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        OrganisationInactive = 106,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        SmsSendFailed = 107,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        InvalidCluster = 108,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        SelectCompanyFailed = 109,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        InvalidLogonServer = 110,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ClientInvalid = 122,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        SameUserIsAlreadyLoggedIn = 168,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        LoggedOffByTwinfield = 169,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        InvalidZlibData = 186,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        InvalidXmlData = 187,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        AccessTokenUserCodeMissing = 351,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        AccessTokenOrganisationCodeMissing = 352,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        AccessTokenOrganisationIdMissing = 353,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        AccessTokenInvalid = 354,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        AccessTokenValidationUnavailable = 358,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        CompanyRequired = 359,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        TokenAndSessionExist = 360,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        CompanyIdAndCodeExist = 361,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        CompanyNotSupported = 362,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ValidationFault", Namespace="http://schemas.datacontract.org/2004/07/Twinfield.WebServices")]
    [System.SerializableAttribute()]
    public partial class ValidationFault : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BankStatementServiceFault", Namespace="http://schemas.datacontract.org/2004/07/Twinfield.WebServices.BankStatementServic" +
        "e")]
    [System.SerializableAttribute()]
    public partial class BankStatementServiceFault : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Code {
            get {
                return this.CodeField;
            }
            set {
                if ((object.ReferenceEquals(this.CodeField, value) != true)) {
                    this.CodeField = value;
                    this.RaisePropertyChanged("Code");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Query", Namespace="http://schemas.datacontract.org/2004/07/Twinfield.WebServices")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(TwinfieldApi.TwinfieldBankStatementService.GetBankStatements))]
    public partial class Query : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetBankStatements", Namespace="http://schemas.datacontract.org/2004/07/Twinfield.WebServices.BankStatementServic" +
        "e")]
    [System.SerializableAttribute()]
    public partial class GetBankStatements : TwinfieldApi.TwinfieldBankStatementService.Query {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IncludePostedStatementsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime StatementDateFromField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime StatementDateToField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IncludePostedStatements {
            get {
                return this.IncludePostedStatementsField;
            }
            set {
                if ((this.IncludePostedStatementsField.Equals(value) != true)) {
                    this.IncludePostedStatementsField = value;
                    this.RaisePropertyChanged("IncludePostedStatements");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime StatementDateFrom {
            get {
                return this.StatementDateFromField;
            }
            set {
                if ((this.StatementDateFromField.Equals(value) != true)) {
                    this.StatementDateFromField = value;
                    this.RaisePropertyChanged("StatementDateFrom");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime StatementDateTo {
            get {
                return this.StatementDateToField;
            }
            set {
                if ((this.StatementDateToField.Equals(value) != true)) {
                    this.StatementDateToField = value;
                    this.RaisePropertyChanged("StatementDateTo");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="QueryResult", Namespace="http://schemas.datacontract.org/2004/07/Twinfield.WebServices")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(TwinfieldApi.TwinfieldBankStatementService.GetBankStatementsResult))]
    public partial class QueryResult : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetBankStatementsResult", Namespace="http://schemas.datacontract.org/2004/07/Twinfield.WebServices.BankStatementServic" +
        "e")]
    [System.SerializableAttribute()]
    public partial class GetBankStatementsResult : TwinfieldApi.TwinfieldBankStatementService.QueryResult {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private TwinfieldApi.TwinfieldBankStatementService.BankStatement[] BankStatementsField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public TwinfieldApi.TwinfieldBankStatementService.BankStatement[] BankStatements {
            get {
                return this.BankStatementsField;
            }
            set {
                if ((object.ReferenceEquals(this.BankStatementsField, value) != true)) {
                    this.BankStatementsField = value;
                    this.RaisePropertyChanged("BankStatements");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BankStatement", Namespace="http://schemas.datacontract.org/2004/07/Twinfield.WebServices.BankStatementServic" +
        "e")]
    [System.SerializableAttribute()]
    public partial class BankStatement : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AccountNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal ClosingBalanceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CurrencyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IbanField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private TwinfieldApi.TwinfieldBankStatementService.BankStatementLine[] LinesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int NumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal OpeningBalanceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime StatementDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int SubIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> TransactionNumberField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AccountNumber {
            get {
                return this.AccountNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.AccountNumberField, value) != true)) {
                    this.AccountNumberField = value;
                    this.RaisePropertyChanged("AccountNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal ClosingBalance {
            get {
                return this.ClosingBalanceField;
            }
            set {
                if ((this.ClosingBalanceField.Equals(value) != true)) {
                    this.ClosingBalanceField = value;
                    this.RaisePropertyChanged("ClosingBalance");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Code {
            get {
                return this.CodeField;
            }
            set {
                if ((object.ReferenceEquals(this.CodeField, value) != true)) {
                    this.CodeField = value;
                    this.RaisePropertyChanged("Code");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Currency {
            get {
                return this.CurrencyField;
            }
            set {
                if ((object.ReferenceEquals(this.CurrencyField, value) != true)) {
                    this.CurrencyField = value;
                    this.RaisePropertyChanged("Currency");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Iban {
            get {
                return this.IbanField;
            }
            set {
                if ((object.ReferenceEquals(this.IbanField, value) != true)) {
                    this.IbanField = value;
                    this.RaisePropertyChanged("Iban");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public TwinfieldApi.TwinfieldBankStatementService.BankStatementLine[] Lines {
            get {
                return this.LinesField;
            }
            set {
                if ((object.ReferenceEquals(this.LinesField, value) != true)) {
                    this.LinesField = value;
                    this.RaisePropertyChanged("Lines");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Number {
            get {
                return this.NumberField;
            }
            set {
                if ((this.NumberField.Equals(value) != true)) {
                    this.NumberField = value;
                    this.RaisePropertyChanged("Number");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal OpeningBalance {
            get {
                return this.OpeningBalanceField;
            }
            set {
                if ((this.OpeningBalanceField.Equals(value) != true)) {
                    this.OpeningBalanceField = value;
                    this.RaisePropertyChanged("OpeningBalance");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime StatementDate {
            get {
                return this.StatementDateField;
            }
            set {
                if ((this.StatementDateField.Equals(value) != true)) {
                    this.StatementDateField = value;
                    this.RaisePropertyChanged("StatementDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int SubId {
            get {
                return this.SubIdField;
            }
            set {
                if ((this.SubIdField.Equals(value) != true)) {
                    this.SubIdField = value;
                    this.RaisePropertyChanged("SubId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> TransactionNumber {
            get {
                return this.TransactionNumberField;
            }
            set {
                if ((this.TransactionNumberField.Equals(value) != true)) {
                    this.TransactionNumberField = value;
                    this.RaisePropertyChanged("TransactionNumber");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BankStatementLine", Namespace="http://schemas.datacontract.org/2004/07/Twinfield.WebServices.BankStatementServic" +
        "e")]
    [System.SerializableAttribute()]
    public partial class BankStatementLine : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private TwinfieldApi.TwinfieldBankStatementService.BankStatementAllocationMethod[] AllocationMethodsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private TwinfieldApi.TwinfieldBankStatementService.BankStatementAllocationRuleStorageLevel AllocationRuleStorageLevelField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private TwinfieldApi.TwinfieldBankStatementService.BankStatementAllocation[] AllocationsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal AmountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal BaseAmountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ContraAccountNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ContraAccountNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ContraIbanField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EndToEndIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int LineIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PaymentReferenceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<TwinfieldApi.TwinfieldBankStatementService.BankStatementAllocationRecognition> RecognitionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ReferenceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ReturnReasonField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TransactionTypeIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public TwinfieldApi.TwinfieldBankStatementService.BankStatementAllocationMethod[] AllocationMethods {
            get {
                return this.AllocationMethodsField;
            }
            set {
                if ((object.ReferenceEquals(this.AllocationMethodsField, value) != true)) {
                    this.AllocationMethodsField = value;
                    this.RaisePropertyChanged("AllocationMethods");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public TwinfieldApi.TwinfieldBankStatementService.BankStatementAllocationRuleStorageLevel AllocationRuleStorageLevel {
            get {
                return this.AllocationRuleStorageLevelField;
            }
            set {
                if ((this.AllocationRuleStorageLevelField.Equals(value) != true)) {
                    this.AllocationRuleStorageLevelField = value;
                    this.RaisePropertyChanged("AllocationRuleStorageLevel");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public TwinfieldApi.TwinfieldBankStatementService.BankStatementAllocation[] Allocations {
            get {
                return this.AllocationsField;
            }
            set {
                if ((object.ReferenceEquals(this.AllocationsField, value) != true)) {
                    this.AllocationsField = value;
                    this.RaisePropertyChanged("Allocations");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Amount {
            get {
                return this.AmountField;
            }
            set {
                if ((this.AmountField.Equals(value) != true)) {
                    this.AmountField = value;
                    this.RaisePropertyChanged("Amount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal BaseAmount {
            get {
                return this.BaseAmountField;
            }
            set {
                if ((this.BaseAmountField.Equals(value) != true)) {
                    this.BaseAmountField = value;
                    this.RaisePropertyChanged("BaseAmount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ContraAccountName {
            get {
                return this.ContraAccountNameField;
            }
            set {
                if ((object.ReferenceEquals(this.ContraAccountNameField, value) != true)) {
                    this.ContraAccountNameField = value;
                    this.RaisePropertyChanged("ContraAccountName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ContraAccountNumber {
            get {
                return this.ContraAccountNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.ContraAccountNumberField, value) != true)) {
                    this.ContraAccountNumberField = value;
                    this.RaisePropertyChanged("ContraAccountNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ContraIban {
            get {
                return this.ContraIbanField;
            }
            set {
                if ((object.ReferenceEquals(this.ContraIbanField, value) != true)) {
                    this.ContraIbanField = value;
                    this.RaisePropertyChanged("ContraIban");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EndToEndId {
            get {
                return this.EndToEndIdField;
            }
            set {
                if ((object.ReferenceEquals(this.EndToEndIdField, value) != true)) {
                    this.EndToEndIdField = value;
                    this.RaisePropertyChanged("EndToEndId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int LineId {
            get {
                return this.LineIdField;
            }
            set {
                if ((this.LineIdField.Equals(value) != true)) {
                    this.LineIdField = value;
                    this.RaisePropertyChanged("LineId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PaymentReference {
            get {
                return this.PaymentReferenceField;
            }
            set {
                if ((object.ReferenceEquals(this.PaymentReferenceField, value) != true)) {
                    this.PaymentReferenceField = value;
                    this.RaisePropertyChanged("PaymentReference");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<TwinfieldApi.TwinfieldBankStatementService.BankStatementAllocationRecognition> Recognition {
            get {
                return this.RecognitionField;
            }
            set {
                if ((this.RecognitionField.Equals(value) != true)) {
                    this.RecognitionField = value;
                    this.RaisePropertyChanged("Recognition");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Reference {
            get {
                return this.ReferenceField;
            }
            set {
                if ((object.ReferenceEquals(this.ReferenceField, value) != true)) {
                    this.ReferenceField = value;
                    this.RaisePropertyChanged("Reference");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ReturnReason {
            get {
                return this.ReturnReasonField;
            }
            set {
                if ((object.ReferenceEquals(this.ReturnReasonField, value) != true)) {
                    this.ReturnReasonField = value;
                    this.RaisePropertyChanged("ReturnReason");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TransactionTypeId {
            get {
                return this.TransactionTypeIdField;
            }
            set {
                if ((object.ReferenceEquals(this.TransactionTypeIdField, value) != true)) {
                    this.TransactionTypeIdField = value;
                    this.RaisePropertyChanged("TransactionTypeId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BankStatementAllocationMethod", Namespace="http://schemas.datacontract.org/2004/07/Twinfield.WebServices.BankStatementServic" +
        "e")]
    [System.SerializableAttribute()]
    public partial class BankStatementAllocationMethod : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> AmountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<TwinfieldApi.TwinfieldBankStatementService.BankStatementAmountOperator> AmountOperatorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TextField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private TwinfieldApi.TwinfieldBankStatementService.BankStatementAllocationMethodType TypeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> Amount {
            get {
                return this.AmountField;
            }
            set {
                if ((this.AmountField.Equals(value) != true)) {
                    this.AmountField = value;
                    this.RaisePropertyChanged("Amount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<TwinfieldApi.TwinfieldBankStatementService.BankStatementAmountOperator> AmountOperator {
            get {
                return this.AmountOperatorField;
            }
            set {
                if ((this.AmountOperatorField.Equals(value) != true)) {
                    this.AmountOperatorField = value;
                    this.RaisePropertyChanged("AmountOperator");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Text {
            get {
                return this.TextField;
            }
            set {
                if ((object.ReferenceEquals(this.TextField, value) != true)) {
                    this.TextField = value;
                    this.RaisePropertyChanged("Text");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public TwinfieldApi.TwinfieldBankStatementService.BankStatementAllocationMethodType Type {
            get {
                return this.TypeField;
            }
            set {
                if ((this.TypeField.Equals(value) != true)) {
                    this.TypeField = value;
                    this.RaisePropertyChanged("Type");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BankStatementAllocationRuleStorageLevel", Namespace="http://schemas.datacontract.org/2004/07/Twinfield.WebServices.BankStatementServic" +
        "e")]
    public enum BankStatementAllocationRuleStorageLevel : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NotStored = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        LocalBank = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        LocalOffice = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        TemplateBank = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        TemplateOffice = 4,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BankStatementAllocation", Namespace="http://schemas.datacontract.org/2004/07/Twinfield.WebServices.BankStatementServic" +
        "e")]
    [System.SerializableAttribute()]
    public partial class BankStatementAllocation : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal AmountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal BaseAmountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ChequeNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionFormatField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Dimension1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Dimension2Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Dimension3Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Dimension4Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Dimension5Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Dimension6Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private TwinfieldApi.TwinfieldBankStatementService.BankStatementMatching[] MatchingsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> PayingInSlipNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool SaveDescriptionFormatToAllocationRuleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private TwinfieldApi.TwinfieldBankStatementService.BankStatementSense SenseField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private TwinfieldApi.TwinfieldBankStatementService.BankStatementAllocationType TypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private TwinfieldApi.TwinfieldBankStatementService.BankStatementVatLine[] VatLinesField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Amount {
            get {
                return this.AmountField;
            }
            set {
                if ((this.AmountField.Equals(value) != true)) {
                    this.AmountField = value;
                    this.RaisePropertyChanged("Amount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal BaseAmount {
            get {
                return this.BaseAmountField;
            }
            set {
                if ((this.BaseAmountField.Equals(value) != true)) {
                    this.BaseAmountField = value;
                    this.RaisePropertyChanged("BaseAmount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ChequeNumber {
            get {
                return this.ChequeNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.ChequeNumberField, value) != true)) {
                    this.ChequeNumberField = value;
                    this.RaisePropertyChanged("ChequeNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DescriptionFormat {
            get {
                return this.DescriptionFormatField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionFormatField, value) != true)) {
                    this.DescriptionFormatField = value;
                    this.RaisePropertyChanged("DescriptionFormat");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Dimension1 {
            get {
                return this.Dimension1Field;
            }
            set {
                if ((object.ReferenceEquals(this.Dimension1Field, value) != true)) {
                    this.Dimension1Field = value;
                    this.RaisePropertyChanged("Dimension1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Dimension2 {
            get {
                return this.Dimension2Field;
            }
            set {
                if ((object.ReferenceEquals(this.Dimension2Field, value) != true)) {
                    this.Dimension2Field = value;
                    this.RaisePropertyChanged("Dimension2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Dimension3 {
            get {
                return this.Dimension3Field;
            }
            set {
                if ((object.ReferenceEquals(this.Dimension3Field, value) != true)) {
                    this.Dimension3Field = value;
                    this.RaisePropertyChanged("Dimension3");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Dimension4 {
            get {
                return this.Dimension4Field;
            }
            set {
                if ((object.ReferenceEquals(this.Dimension4Field, value) != true)) {
                    this.Dimension4Field = value;
                    this.RaisePropertyChanged("Dimension4");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Dimension5 {
            get {
                return this.Dimension5Field;
            }
            set {
                if ((object.ReferenceEquals(this.Dimension5Field, value) != true)) {
                    this.Dimension5Field = value;
                    this.RaisePropertyChanged("Dimension5");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Dimension6 {
            get {
                return this.Dimension6Field;
            }
            set {
                if ((object.ReferenceEquals(this.Dimension6Field, value) != true)) {
                    this.Dimension6Field = value;
                    this.RaisePropertyChanged("Dimension6");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public TwinfieldApi.TwinfieldBankStatementService.BankStatementMatching[] Matchings {
            get {
                return this.MatchingsField;
            }
            set {
                if ((object.ReferenceEquals(this.MatchingsField, value) != true)) {
                    this.MatchingsField = value;
                    this.RaisePropertyChanged("Matchings");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> PayingInSlipNumber {
            get {
                return this.PayingInSlipNumberField;
            }
            set {
                if ((this.PayingInSlipNumberField.Equals(value) != true)) {
                    this.PayingInSlipNumberField = value;
                    this.RaisePropertyChanged("PayingInSlipNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool SaveDescriptionFormatToAllocationRule {
            get {
                return this.SaveDescriptionFormatToAllocationRuleField;
            }
            set {
                if ((this.SaveDescriptionFormatToAllocationRuleField.Equals(value) != true)) {
                    this.SaveDescriptionFormatToAllocationRuleField = value;
                    this.RaisePropertyChanged("SaveDescriptionFormatToAllocationRule");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public TwinfieldApi.TwinfieldBankStatementService.BankStatementSense Sense {
            get {
                return this.SenseField;
            }
            set {
                if ((this.SenseField.Equals(value) != true)) {
                    this.SenseField = value;
                    this.RaisePropertyChanged("Sense");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public TwinfieldApi.TwinfieldBankStatementService.BankStatementAllocationType Type {
            get {
                return this.TypeField;
            }
            set {
                if ((this.TypeField.Equals(value) != true)) {
                    this.TypeField = value;
                    this.RaisePropertyChanged("Type");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public TwinfieldApi.TwinfieldBankStatementService.BankStatementVatLine[] VatLines {
            get {
                return this.VatLinesField;
            }
            set {
                if ((object.ReferenceEquals(this.VatLinesField, value) != true)) {
                    this.VatLinesField = value;
                    this.RaisePropertyChanged("VatLines");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BankStatementAllocationRecognition", Namespace="http://schemas.datacontract.org/2004/07/Twinfield.WebServices.BankStatementServic" +
        "e")]
    public enum BankStatementAllocationRecognition : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        AllocationRule = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ContraAccountNumber = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ContraIban = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        InvoiceNumber = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        RelationCode = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ChequeNumber = 5,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        PayingInSlipNumber = 6,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        PaymentResult = 7,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BankStatementAmountOperator", Namespace="http://schemas.datacontract.org/2004/07/Twinfield.WebServices.BankStatementServic" +
        "e")]
    public enum BankStatementAmountOperator : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Equal = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NotEqual = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        LessThan = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        LessThanOrEqualTo = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        MoreThan = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        MoreThanOrEqualTo = 5,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BankStatementAllocationMethodType", Namespace="http://schemas.datacontract.org/2004/07/Twinfield.WebServices.BankStatementServic" +
        "e")]
    public enum BankStatementAllocationMethodType : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Description = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ContraAccountNumber = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ContraIban = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ContraAccountName = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        TransactionTypeId = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Reference = 5,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Amount = 6,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BankStatementMatching", Namespace="http://schemas.datacontract.org/2004/07/Twinfield.WebServices.BankStatementServic" +
        "e")]
    [System.SerializableAttribute()]
    public partial class BankStatementMatching : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal BaseValueField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int LineIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal NumberField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal BaseValue {
            get {
                return this.BaseValueField;
            }
            set {
                if ((this.BaseValueField.Equals(value) != true)) {
                    this.BaseValueField = value;
                    this.RaisePropertyChanged("BaseValue");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Code {
            get {
                return this.CodeField;
            }
            set {
                if ((object.ReferenceEquals(this.CodeField, value) != true)) {
                    this.CodeField = value;
                    this.RaisePropertyChanged("Code");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int LineId {
            get {
                return this.LineIdField;
            }
            set {
                if ((this.LineIdField.Equals(value) != true)) {
                    this.LineIdField = value;
                    this.RaisePropertyChanged("LineId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Number {
            get {
                return this.NumberField;
            }
            set {
                if ((this.NumberField.Equals(value) != true)) {
                    this.NumberField = value;
                    this.RaisePropertyChanged("Number");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BankStatementSense", Namespace="http://schemas.datacontract.org/2004/07/Twinfield.WebServices.BankStatementServic" +
        "e")]
    public enum BankStatementSense : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Debit = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Credit = 1,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BankStatementAllocationType", Namespace="http://schemas.datacontract.org/2004/07/Twinfield.WebServices.BankStatementServic" +
        "e")]
    public enum BankStatementAllocationType : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Suspense = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        GeneralLedger = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Customer = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Supplier = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        SupplierCheque = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        PayingInSlip = 5,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BankStatementVatLine", Namespace="http://schemas.datacontract.org/2004/07/Twinfield.WebServices.BankStatementServic" +
        "e")]
    [System.SerializableAttribute()]
    public partial class BankStatementVatLine : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal TurnoverField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal ValueField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool ValueOverriddenField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Code {
            get {
                return this.CodeField;
            }
            set {
                if ((object.ReferenceEquals(this.CodeField, value) != true)) {
                    this.CodeField = value;
                    this.RaisePropertyChanged("Code");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Turnover {
            get {
                return this.TurnoverField;
            }
            set {
                if ((this.TurnoverField.Equals(value) != true)) {
                    this.TurnoverField = value;
                    this.RaisePropertyChanged("Turnover");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Value {
            get {
                return this.ValueField;
            }
            set {
                if ((this.ValueField.Equals(value) != true)) {
                    this.ValueField = value;
                    this.RaisePropertyChanged("Value");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool ValueOverridden {
            get {
                return this.ValueOverriddenField;
            }
            set {
                if ((this.ValueOverriddenField.Equals(value) != true)) {
                    this.ValueOverriddenField = value;
                    this.RaisePropertyChanged("ValueOverridden");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.twinfield.com/", ConfigurationName="TwinfieldBankStatementService.BankStatementService")]
    public interface BankStatementService {
        
        // CODEGEN: Generating message contract since the operation Process is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://www.twinfield.com/BankStatementService/Process", ReplyAction="http://www.twinfield.com/BankStatementService/ProcessResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(TwinfieldApi.TwinfieldBankStatementService.SecurityFault), Action="http://www.twinfield.com/BankStatementService/ProcessSecurityFaultFault", Name="SecurityFault", Namespace="http://schemas.datacontract.org/2004/07/Twinfield.WebServices")]
        [System.ServiceModel.FaultContractAttribute(typeof(TwinfieldApi.TwinfieldBankStatementService.ValidationFault), Action="http://www.twinfield.com/BankStatementService/ProcessValidationFaultFault", Name="ValidationFault", Namespace="http://schemas.datacontract.org/2004/07/Twinfield.WebServices")]
        [System.ServiceModel.FaultContractAttribute(typeof(TwinfieldApi.TwinfieldBankStatementService.BankStatementServiceFault), Action="http://www.twinfield.com/BankStatementService/ProcessBankStatementServiceFaultFau" +
            "lt", Name="BankStatementServiceFault", Namespace="http://schemas.datacontract.org/2004/07/Twinfield.WebServices.BankStatementServic" +
            "e")]
        TwinfieldApi.TwinfieldBankStatementService.ProcessResponse Process(TwinfieldApi.TwinfieldBankStatementService.CommandRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.twinfield.com/BankStatementService/Process", ReplyAction="http://www.twinfield.com/BankStatementService/ProcessResponse")]
        System.Threading.Tasks.Task<TwinfieldApi.TwinfieldBankStatementService.ProcessResponse> ProcessAsync(TwinfieldApi.TwinfieldBankStatementService.CommandRequest request);
        
        // CODEGEN: Generating message contract since the operation Query is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://www.twinfield.com/BankStatementService/Query", ReplyAction="http://www.twinfield.com/BankStatementService/QueryResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(TwinfieldApi.TwinfieldBankStatementService.SecurityFault), Action="http://www.twinfield.com/BankStatementService/QuerySecurityFaultFault", Name="SecurityFault", Namespace="http://schemas.datacontract.org/2004/07/Twinfield.WebServices")]
        [System.ServiceModel.FaultContractAttribute(typeof(TwinfieldApi.TwinfieldBankStatementService.ValidationFault), Action="http://www.twinfield.com/BankStatementService/QueryValidationFaultFault", Name="ValidationFault", Namespace="http://schemas.datacontract.org/2004/07/Twinfield.WebServices")]
        [System.ServiceModel.FaultContractAttribute(typeof(TwinfieldApi.TwinfieldBankStatementService.BankStatementServiceFault), Action="http://www.twinfield.com/BankStatementService/QueryBankStatementServiceFaultFault" +
            "", Name="BankStatementServiceFault", Namespace="http://schemas.datacontract.org/2004/07/Twinfield.WebServices.BankStatementServic" +
            "e")]
        TwinfieldApi.TwinfieldBankStatementService.QueryResponse Query(TwinfieldApi.TwinfieldBankStatementService.QueryRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.twinfield.com/BankStatementService/Query", ReplyAction="http://www.twinfield.com/BankStatementService/QueryResponse")]
        System.Threading.Tasks.Task<TwinfieldApi.TwinfieldBankStatementService.QueryResponse> QueryAsync(TwinfieldApi.TwinfieldBankStatementService.QueryRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CommandRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://www.twinfield.com/")]
        public TwinfieldApi.TwinfieldBankStatementService.AuthenticationHeader Authentication;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://www.twinfield.com/")]
        public string SessionId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.twinfield.com/", Order=0)]
        public TwinfieldApi.TwinfieldBankStatementService.Command Command;
        
        public CommandRequest() {
        }
        
        public CommandRequest(TwinfieldApi.TwinfieldBankStatementService.AuthenticationHeader Authentication, string SessionId, TwinfieldApi.TwinfieldBankStatementService.Command Command) {
            this.Authentication = Authentication;
            this.SessionId = SessionId;
            this.Command = Command;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ProcessResponse {
        
        public ProcessResponse() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class QueryRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://www.twinfield.com/")]
        public TwinfieldApi.TwinfieldBankStatementService.AuthenticationHeader Authentication;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://www.twinfield.com/")]
        public string SessionId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.twinfield.com/", Order=0)]
        public TwinfieldApi.TwinfieldBankStatementService.Query Query;
        
        public QueryRequest() {
        }
        
        public QueryRequest(TwinfieldApi.TwinfieldBankStatementService.AuthenticationHeader Authentication, string SessionId, TwinfieldApi.TwinfieldBankStatementService.Query Query) {
            this.Authentication = Authentication;
            this.SessionId = SessionId;
            this.Query = Query;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class QueryResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.twinfield.com/", Order=0)]
        public TwinfieldApi.TwinfieldBankStatementService.QueryResult Result;
        
        public QueryResponse() {
        }
        
        public QueryResponse(TwinfieldApi.TwinfieldBankStatementService.QueryResult Result) {
            this.Result = Result;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface BankStatementServiceChannel : TwinfieldApi.TwinfieldBankStatementService.BankStatementService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class BankStatementServiceClient : System.ServiceModel.ClientBase<TwinfieldApi.TwinfieldBankStatementService.BankStatementService>, TwinfieldApi.TwinfieldBankStatementService.BankStatementService {
        
        public BankStatementServiceClient() {
        }
        
        public BankStatementServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public BankStatementServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BankStatementServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BankStatementServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TwinfieldApi.TwinfieldBankStatementService.ProcessResponse TwinfieldApi.TwinfieldBankStatementService.BankStatementService.Process(TwinfieldApi.TwinfieldBankStatementService.CommandRequest request) {
            return base.Channel.Process(request);
        }
        
        public void Process(TwinfieldApi.TwinfieldBankStatementService.AuthenticationHeader Authentication, string SessionId, TwinfieldApi.TwinfieldBankStatementService.Command Command) {
            TwinfieldApi.TwinfieldBankStatementService.CommandRequest inValue = new TwinfieldApi.TwinfieldBankStatementService.CommandRequest();
            inValue.Authentication = Authentication;
            inValue.SessionId = SessionId;
            inValue.Command = Command;
            TwinfieldApi.TwinfieldBankStatementService.ProcessResponse retVal = ((TwinfieldApi.TwinfieldBankStatementService.BankStatementService)(this)).Process(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TwinfieldApi.TwinfieldBankStatementService.ProcessResponse> TwinfieldApi.TwinfieldBankStatementService.BankStatementService.ProcessAsync(TwinfieldApi.TwinfieldBankStatementService.CommandRequest request) {
            return base.Channel.ProcessAsync(request);
        }
        
        public System.Threading.Tasks.Task<TwinfieldApi.TwinfieldBankStatementService.ProcessResponse> ProcessAsync(TwinfieldApi.TwinfieldBankStatementService.AuthenticationHeader Authentication, string SessionId, TwinfieldApi.TwinfieldBankStatementService.Command Command) {
            TwinfieldApi.TwinfieldBankStatementService.CommandRequest inValue = new TwinfieldApi.TwinfieldBankStatementService.CommandRequest();
            inValue.Authentication = Authentication;
            inValue.SessionId = SessionId;
            inValue.Command = Command;
            return ((TwinfieldApi.TwinfieldBankStatementService.BankStatementService)(this)).ProcessAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TwinfieldApi.TwinfieldBankStatementService.QueryResponse TwinfieldApi.TwinfieldBankStatementService.BankStatementService.Query(TwinfieldApi.TwinfieldBankStatementService.QueryRequest request) {
            return base.Channel.Query(request);
        }
        
        public TwinfieldApi.TwinfieldBankStatementService.QueryResult Query(TwinfieldApi.TwinfieldBankStatementService.AuthenticationHeader Authentication, string SessionId, TwinfieldApi.TwinfieldBankStatementService.Query Query1) {
            TwinfieldApi.TwinfieldBankStatementService.QueryRequest inValue = new TwinfieldApi.TwinfieldBankStatementService.QueryRequest();
            inValue.Authentication = Authentication;
            inValue.SessionId = SessionId;
            inValue.Query = Query1;
            TwinfieldApi.TwinfieldBankStatementService.QueryResponse retVal = ((TwinfieldApi.TwinfieldBankStatementService.BankStatementService)(this)).Query(inValue);
            return retVal.Result;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TwinfieldApi.TwinfieldBankStatementService.QueryResponse> TwinfieldApi.TwinfieldBankStatementService.BankStatementService.QueryAsync(TwinfieldApi.TwinfieldBankStatementService.QueryRequest request) {
            return base.Channel.QueryAsync(request);
        }
        
        public System.Threading.Tasks.Task<TwinfieldApi.TwinfieldBankStatementService.QueryResponse> QueryAsync(TwinfieldApi.TwinfieldBankStatementService.AuthenticationHeader Authentication, string SessionId, TwinfieldApi.TwinfieldBankStatementService.Query Query) {
            TwinfieldApi.TwinfieldBankStatementService.QueryRequest inValue = new TwinfieldApi.TwinfieldBankStatementService.QueryRequest();
            inValue.Authentication = Authentication;
            inValue.SessionId = SessionId;
            inValue.Query = Query;
            return ((TwinfieldApi.TwinfieldBankStatementService.BankStatementService)(this)).QueryAsync(inValue);
        }

        public void Process(string SessionId, Command Command)
        {
            TwinfieldApi.TwinfieldBankStatementService.CommandRequest inValue = new TwinfieldApi.TwinfieldBankStatementService.CommandRequest();
            inValue.SessionId = SessionId;
            inValue.Command = Command;
            TwinfieldApi.TwinfieldBankStatementService.ProcessResponse retVal =
                ((TwinfieldApi.TwinfieldBankStatementService.BankStatementService) (this)).Process(inValue);
        }

        public QueryResult Query(string SessionId, Query Query)
        {
            TwinfieldApi.TwinfieldBankStatementService.QueryRequest inValue = new TwinfieldApi.TwinfieldBankStatementService.QueryRequest();
            inValue.SessionId = SessionId;
            inValue.Query = Query;
            TwinfieldApi.TwinfieldBankStatementService.QueryResponse retVal =
                ((TwinfieldApi.TwinfieldBankStatementService.BankStatementService) (this)).Query(inValue);
            return retVal.Result;
        }
    }
}
